const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync('src/Fittings.tsx', 'utf8');
const eve = fs.readFileSync('electron/eve.ts', 'utf8');

assert.match(source, /Import current EVE fit/);
assert.match(source, /currentEveFitFromSnapshot/);
assert.match(eve, /characters\/\$\{characterId\}\/assets\//, 'current-ship refresh must refresh fitted assets');
assert.doesNotMatch(source, /@npc:abyssal/, 'fitter must not preload the entire Abyss NPC catalogue');
assert.doesNotMatch(source, /targetDamageProfilePreset/, 'dead Pyfa-style DEAL preset must stay removed');

assert.match(source, /setTab\("scenario"\)/, 'Combat Scenario must be a top-level fitter tab');
assert.match(source, /function FitCombatScenario/);
assert.match(source, /Abyssal Deadspace/);
assert.match(source, /\[0,1,2,3,4,5,6\]/, 'Abyss selector must expose T0-T6');
assert.match(source, /<span>Tier<\/span>/);
assert.match(source, /<span>Weather<\/span>/);
assert.match(source, /DED complexes & escalations/);
assert.match(source, /The Maze/);
assert.match(source, /Mul-Zatah Monastery/);
assert.doesNotMatch(source, /9\/10 DED complex/, 'there is no 9/10 DED complex');
assert.match(source, /Sansha Incursions/);
assert.match(source, /Homefront Operations/);
assert.match(source, /Wormhole Sleeper PvE/);
assert.match(source, /Pochven combat/);
assert.match(source, /Combat exploration & hazardous sites/);
assert.match(source, /Pirate FOB \/ Stronghold/);
assert.match(source, /Limited-time combat event/);
assert.match(source, /Run strategy/);
assert.match(source, /m sig · .*km range/, 'Target model must label signature and range explicitly');
assert.doesNotMatch(source, / m μ /, 'Target model must not use the stray mu separator');
assert.match(source, /Active fitted drone flight/);
assert.match(source, /Auto \/ best legal flight/);
assert.match(source, /Room breakdown & exact NPC data/);
assert.match(source, /Avg drone travel/);
assert.match(source, /target-to-target drone switch/);
assert.match(source, /Worst-case 3-room total/);
assert.match(source, /siteEstimate\?\.heavyKnown\?\.estimatedClearSeconds/);
assert.match(source, /Includes mobile-drone launch and target-to-target travel/);
assert.match(source, /hull is not assumed to move between targets/);
assert.match(source, /not a guarantee/);assert.match(source, /Tank stable/);
assert.match(source, /Tank holds/);
assert.match(source, /Tank breaks/);
assert.match(source, /Tank stable indefinitely/);
assert.match(source, /Tank stable/);
assert.match(source, /Tank holds while cap lasts -/);
assert.match(source, /Tank breaks/);
assert.match(source, /averageTankCapStable/);
assert.match(source, /EHP\/s effective tank vs/);
assert.match(source, /includes current reps, passive regen and resists/);
assert.match(source, /fit-rail-target-application/);
assert.match(source, /Target &amp; application/);
assert.doesNotMatch(source, /Advanced manual target & application/);
assert.doesNotMatch(source, /<section className="fit-rail-section combat-scenario-card">/);
assert.match(source, /getFittingChargesForModulesLocal/);
assert.doesNotMatch(source, /<h3>Damage profile<\/h3>/);
assert.doesNotMatch(source, /<h3>Target application<\/h3>/);
console.log('fitter-combat-scenario-ui: ok');
