const assert=require('node:assert/strict');
const {analyzePlanetaryRevenue,buildPlanetaryPlan,calculateExtractorCycleValues}=require('../../dist-electron/planetary-revenue.js');
const {buildOptimizerFromAnalysis,buildPlanetaryAlertQueue,buildPlanetaryBasketPlan,evaluatePlanetaryDesignerLayout,generatePlanetaryDesignerLayouts,buildPlanetaryDesignerEveTemplate}=require('../../dist-electron/planetary-advanced.js');

function referenceExtractor(qty,cycle,total,decay=.012,noise=.8){const out=[];const w=cycle/900;for(let i=0;i<total;i++){const t=(i+.5)*w;const d=qty/(1+t*decay);const phase=Math.pow(qty,.7);const s=Math.max((Math.cos(phase+t/12)+Math.cos(phase/2+t*.2)+Math.cos(t*.5))/3,0);const value=w*d*(1+noise*s);out.push(Math.max(0,Math.ceil(value)-1));}return out;}
const skills=[
  {skill_id:2495,trained_skill_level:5,name:'Interplanetary Consolidation'},
  {skill_id:2505,trained_skill_level:5,name:'Command Center Upgrades'},
  {skill_id:2406,trained_skill_level:4,name:'Planetology'},
  {skill_id:2403,trained_skill_level:3,name:'Advanced Planetology'},
  {skill_id:13279,trained_skill_level:3,name:'Remote Sensing'},
  {skill_id:16622,trained_skill_level:5,name:'Accounting'},
  {skill_id:3446,trained_skill_level:5,name:'Broker Relations'},
  {skill_id:33467,trained_skill_level:0,name:'Customs Code Expertise'},
];
const base={characterId:'999999999',character:{name:'PI Smoke'},skills:{skills},extended:{planets:[],planetDetails:[],assets:[],industryJobs:[]},location:{solar_system_id:30000001,solar_system_name:'Tanoo'}};
(async()=>{
  const ref=referenceExtractor(6965,1800,95);const actual=calculateExtractorCycleValues(6965,1800,95);assert.deepEqual(actual,ref);assert.equal(actual.length,95);console.log('extractor',actual.slice(0,5).join(','),'total',actual.reduce((a,b)=>a+b,0));

  const settings={pocoOwnerTaxPercent:0,assumedSecurity:'high',brokerFeePercent:null,cargoM3:10000,haulingCostPerTripIsk:0,maxJumps:10,runtimeHours:24};
  const analysis=await analyzePlanetaryRevenue(base,[base],settings);assert.equal(analysis.opportunities.length,68);const p2=analysis.opportunities.find(x=>x.tier==='P2'&&x.fullyPriced);assert.ok(p2,'priced P2 recipe');
  const expectedExport=p2.output.quantityPerDay*7200*.10;const expectedImport=p2.inputs.reduce((s,x)=>s+x.quantityPerDay*400*.10*.5,0);assert.ok(Math.abs(p2.exportTaxPerDay-expectedExport)<.001);assert.ok(Math.abs(p2.importTaxPerDay-expectedImport)<.001);assert.ok(Math.abs(analysis.settings.salesTaxPercent-3.375)<1e-9);const costlyAnalysis=await analyzePlanetaryRevenue(base,[base],{...settings,haulingCostPerTripIsk:1_000_000});const costlyP2=costlyAnalysis.opportunities.find(x=>x.schematicId===p2.schematicId);assert.ok(costlyP2.haulingCostPerDay>0);assert.ok(costlyP2.taxAdjustedMarginPerDay<p2.taxAdjustedMarginPerDay);console.log('tax',p2.output.name,'export',p2.exportTaxPerDay,'import',p2.importTaxPerDay,'net',p2.taxAdjustedMarginPerDay);

  const p1=analysis.opportunities.find(x=>x.tier==='P1');assert.ok(p1);const rawType=p1.inputs[0].typeId;const launchpadContents=p2.inputs.map(x=>({type_id:x.typeId,amount:Math.ceil(x.quantityPerDay*2)}));
  const planetSummary={planet_id:40000002,solar_system_id:30000001,planet_type:'temperate',upgrade_level:5,num_pins:2,last_update:new Date().toISOString()};
  const healthyColony={pins:[{pin_id:1,type_id:2256,contents:launchpadContents},{pin_id:2,type_id:2480,factory_details:{schematic_id:p2.schematicId},contents:[]},{pin_id:3,type_id:3068,install_time:new Date(Date.now()-2*3600000).toISOString(),expiry_time:new Date(Date.now()+30*3600000).toISOString(),extractor_details:{cycle_time:1800,qty_per_cycle:100,product_type_id:rawType,heads:[{head_id:1,latitude:0,longitude:0}]},contents:[]}],links:[{source_pin_id:1,destination_pin_id:2,link_level:0},{source_pin_id:3,destination_pin_id:1,link_level:0}],routes:[...p2.inputs.map((x,i)=>({route_id:i+1,source_pin_id:1,destination_pin_id:2,content_type_id:x.typeId,quantity:x.quantityPerCycle,waypoints:[]})),{route_id:99,source_pin_id:2,destination_pin_id:1,content_type_id:p2.output.typeId,quantity:p2.output.quantityPerCycle,waypoints:[]},{route_id:100,source_pin_id:3,destination_pin_id:1,content_type_id:rawType,quantity:100,waypoints:[]}]};
  const live={...base,extended:{...base.extended,planets:[planetSummary],planetDetails:[{planetId:40000002,colony:healthyColony}]}};
  const liveAnalysis=await analyzePlanetaryRevenue(live,[live],settings);const colony=liveAnalysis.colonies[0];assert.ok(colony);assert.equal(colony.badRoutes,0);assert.equal(colony.starvedProcessors,0);assert.equal(colony.unroutedProcessors,0);assert.equal(colony.healthScore,100);assert.ok(colony.processorsHealth[0].lowestHoursRemaining>24);assert.equal(colony.extractors.length,1);assert.equal(colony.extractors[0].unrouted,false);assert.notEqual(colony.extractors[0].next24hUnits,100*48);console.log('healthy-colony',colony.healthScore,'buffer',colony.processorsHealth[0].lowestHoursRemaining,'extractor24',colony.extractors[0].next24hUnits);

  const broken=structuredClone(live);broken.extended.planetDetails[0].colony.routes[0].waypoints=[999999];const brokenAnalysis=await analyzePlanetaryRevenue(broken,[broken],settings);const brokenColony=brokenAnalysis.colonies[0];assert.ok(brokenColony.badRoutes>=1);assert.ok(brokenColony.starvedProcessors>=1);assert.ok(brokenAnalysis.empire.alerts.some(x=>x.type==='broken-route'));console.log('broken-colony',brokenColony.healthScore,'badRoutes',brokenColony.badRoutes,'starved',brokenColony.starvedProcessors);

  const stocked={...base,extended:{...base.extended,assets:p2.inputs.map((x,i)=>({item_id:100+i,type_id:x.typeId,quantity:1_000_000,station:'Jita'}))}};
  const buyPlan=await buildPlanetaryPlan(stocked,[stocked],{...settings,characterId:stocked.characterId,productTypeId:p2.output.typeId,finalProcessors:1,mode:'buy',originSystemId:30000001,planetTypeId:11,finderSecurity:'any',resourceObservations:[]});
  assert.ok(buyPlan.refill.every(x=>x.shortage===0));assert.equal(buyPlan.layout.fits,true);assert.equal(buyPlan.layout.ccuLevel,5);assert.ok(buyPlan.layout.cpuCapacity>buyPlan.layout.cpuUsed);assert.ok(buyPlan.eveTemplate&&Array.isArray(buyPlan.eveTemplate.P)&&Array.isArray(buyPlan.eveTemplate.L)&&Array.isArray(buyPlan.eveTemplate.R));assert.equal(buyPlan.eveTemplate.P.length,2);assert.equal(buyPlan.eveTemplate.P[1].S,p2.output.typeId);assert.equal(buyPlan.eveTemplate.L.length,1);assert.equal(buyPlan.eveTemplate.R.length,p2.inputs.length+1);assert.ok(Math.abs((buyPlan.layout.facilityCpuUsed+buyPlan.layout.linkCpu)-buyPlan.layout.cpuUsed)<1e-6);assert.ok(Math.abs((buyPlan.layout.facilityPowerUsed+buyPlan.layout.linkPower)-buyPlan.layout.powerUsed)<1e-6);assert.ok(buyPlan.sourceDecisions.some(x=>x.decision==='BUY'));assert.equal(buyPlan.target.haulingCostPerDay,0);console.log('layout',buyPlan.layout.planetType,buyPlan.layout.cpuUsed,'/',buyPlan.layout.cpuCapacity,buyPlan.layout.powerUsed,'/',buyPlan.layout.powerCapacity,'template routes',buyPlan.eveTemplate.R.length);

  const fullPlan=await buildPlanetaryPlan(base,[base],{...settings,characterId:base.characterId,productTypeId:p2.output.typeId,finalProcessors:1,mode:'full',originSystemId:30000001,maxJumps:10,finderSecurity:'any',resourceObservations:[]});assert.ok(fullPlan.chain.rawResourceIds.length>=2);assert.ok(fullPlan.systemFinder.systems.length>0);assert.ok(fullPlan.systemFinder.planets.length>0);assert.ok(fullPlan.allocation.requiredColonies>=2);assert.ok(fullPlan.chain.processors.some(x=>x.tier==='P1'));assert.ok(fullPlan.sourceDecisions.some(x=>x.decision==='EXTRACT'&&x.tier==='P0'));assert.ok(fullPlan.sourceDecisions.some(x=>x.decision==='PRODUCE'));console.log('finder',fullPlan.chain.rawResources.map(x=>x.name).join(' + '),'systems',fullPlan.systemFinder.systems.length,'best',fullPlan.systemFinder.systems[0]?.systemName,fullPlan.systemFinder.systems[0]?.coveragePercent);

  const hybrid=await buildPlanetaryPlan(base,[base],{...settings,characterId:base.characterId,productTypeId:p2.output.typeId,finalProcessors:1,mode:'hybrid',hybridBuildTypeIds:[],originSystemId:30000001,maxJumps:10,finderSecurity:'any',resourceObservations:[]});assert.equal(hybrid.chain.processors.length,1);assert.ok(Array.isArray(hybrid.hybridCandidates));console.log('hybrid candidates',hybrid.hybridCandidates.length,'explicit-buy processors',hybrid.chain.processors.length);
  const costlyPlan=await buildPlanetaryPlan(stocked,[stocked],{...settings,haulingCostPerTripIsk:1_000_000,characterId:stocked.characterId,productTypeId:p2.output.typeId,finalProcessors:1,mode:'buy',originSystemId:30000001,planetTypeId:11,finderSecurity:'any',resourceObservations:[]});assert.ok(costlyPlan.hauling.costPerWeek>0);assert.ok(costlyPlan.target.haulingCostPerDay>0);assert.ok(costlyPlan.target.taxAdjustedProfitPerDay<buyPlan.target.taxAdjustedProfitPerDay);
  const densitySystem=fullPlan.systemFinder.systems.find(row=>row.fullCoverage);assert.ok(densitySystem,'full-coverage density system');const densityObs=fullPlan.chain.rawResourceIds.map((resourceId,index)=>{const planet=fullPlan.systemFinder.planets.find(row=>row.systemId===densitySystem.systemId&&row.resources.some(resource=>resource.typeId===resourceId));assert.ok(planet,`planet for raw resource ${resourceId}`);const resource=planet.resources.find(row=>row.typeId===resourceId);return {planetId:planet.planetId,systemId:planet.systemId,systemName:planet.systemName,planetTypeId:planet.planetTypeId,planetType:planet.planetType,radiusKm:planet.radiusKm,resourceTypeId:resourceId,resourceName:resource?.name,percent:index===0?84:78,confidence:.9,scope:'personal',source:'test',observedAt:'2026-08-21T12:00:00.000Z'};});const densityPlan=await buildPlanetaryPlan(base,[base],{...settings,characterId:base.characterId,productTypeId:p2.output.typeId,finalProcessors:1,mode:'full',originSystemId:30000001,maxJumps:10,finderSecurity:'any',resourceObservations:densityObs});const densitySystemRow=densityPlan.systemFinder.systems.find(row=>row.systemId===densitySystem.systemId);assert.ok(densitySystemRow);assert.equal(Math.round(densitySystemRow.densityBottleneckPercent),78);assert.equal(Math.round(densitySystemRow.densityKnownPercent),100);const observedPlanet=densityPlan.systemFinder.planets.find(row=>row.planetId===densityObs[0].planetId);assert.ok(observedPlanet&&observedPlanet.densityBottleneckPercent!=null);const unknownDensity=densityPlan.systemFinder.systems.find(row=>row.systemId!==densitySystem.systemId&&row.fullCoverage);if(unknownDensity)assert.equal(unknownDensity.densityBottleneckPercent,null);console.log('density-bottleneck',densitySystemRow.systemName,densitySystemRow.densityBottleneckPercent,densitySystemRow.densityKnownPercent);

  const optimizer=buildOptimizerFromAnalysis(brokenAnalysis,densityObs);assert.ok(optimizer.recommendations.some(row=>row.kind==='repair-routes'));assert.ok(optimizer.recommendations.find(row=>row.kind==='repair-routes').rank<=2);const alertQueue=buildPlanetaryAlertQueue(brokenAnalysis,optimizer,{enabled:{'broken-route':true,'factory-starvation':true,'optimizer-value':true},optimizerMinIskPerDay:0});assert.ok(alertQueue.some(row=>row.type==='broken-route'||row.type==='extractor-unrouted'||row.type==='output-unrouted'));console.log('optimizer',optimizer.recommendations.slice(0,3).map(row=>row.kind).join(','),'alerts',alertQueue.length);

  const basket=await buildPlanetaryBasketPlan(base,[base],analysis,{...settings,characterId:base.characterId,targets:[{typeId:p2.output.typeId,quantity:4000,period:'week'},{typeId:p1.output.typeId,quantity:8000,period:'week'}],mode:'full',originSystemId:30000001,maxJumps:10,finderSecurity:'any',horizonDays:7,resourceObservations:densityObs});assert.equal(basket.targets.length,2);assert.ok(basket.processors.length>=2);assert.equal(new Set(basket.processors.map(row=>row.schematicId)).size,basket.processors.length);assert.ok(basket.externalInputs.length>=1);assert.ok(basket.allocation.planetsRequired>=1);assert.ok(basket.economics.marketBuyCostPerWeek!=null);console.log('basket',basket.targets.map(row=>row.name).join('+'),'processors',basket.processors.length,'planets',basket.allocation.planetsRequired);

  const palette=buyPlan.layout.designerPalette;assert.ok(Array.isArray(palette)&&palette.length>0);const launch=palette.find(row=>row.kind==='launchpad');const basic=palette.find(row=>row.kind==='basic')??palette.find(row=>row.kind==='advanced');assert.ok(launch&&basic);const designerBase={planetTypeId:buyPlan.layout.planetTypeId,planetType:buyPlan.layout.planetType,planetRadiusKm:buyPlan.layout.planetRadiusKm,ccuLevel:buyPlan.layout.ccuLevel,commandCenter:buyPlan.layout.commandCenter,palette,nodes:[{id:'l',typeId:launch.typeId,x:0,y:0,label:'Launchpad'},{id:'p',typeId:basic.typeId,x:.1,y:0,label:'Processor',inputM3PerHour:10,outputM3PerHour:2,inputUnitsPerHour:100,outputUnitsPerHour:20}],links:[{sourceId:'l',destinationId:'p',level:0}]};const near=evaluatePlanetaryDesignerLayout(designerBase);const far=evaluatePlanetaryDesignerLayout({...designerBase,nodes:[designerBase.nodes[0],{...designerBase.nodes[1],x:.9,y:.9}]});assert.equal(Math.round(near.facilityCpu),Math.round(launch.cpu+basic.cpu));assert.ok(near.linkCpu>0);assert.ok(far.linkCpu>near.linkCpu);assert.ok(near.storageCapacityM3>=launch.capacityM3);assert.equal(typeof near.firstBottleneck,'string');console.log('designer','near-link',near.linkCpu,'far-link',far.linkCpu,'buffer',near.bufferHours);
  const suggested=generatePlanetaryDesignerLayouts({...designerBase,targetTypeId:p2.output.typeId,nodes:[{...designerBase.nodes[0],templatePinIndex:1},{...designerBase.nodes[1],templatePinIndex:2,productTypeId:p2.output.typeId}]});assert.equal(suggested.length,3);assert.deepEqual(suggested.map(x=>x.profile),['throughput','balanced','maintenance']);assert.ok(suggested[0].result.linkCpu<near.linkCpu);assert.ok(suggested.every(x=>x.layout.nodes.length>=designerBase.nodes.length));const exported=buildPlanetaryDesignerEveTemplate(suggested[0].layout,buyPlan.eveTemplate,'Sage regression layout');assert.ok(exported.template);assert.equal(exported.template.P.length,2);assert.equal(exported.template.P[1].S,p2.output.typeId);assert.ok(exported.template.L.length>=1);assert.equal(exported.template.R.length,buyPlan.eveTemplate.R.length);console.log('designer-optimal',suggested.map(x=>x.profile+':'+Math.round(x.result.linkCpu)).join(','),'eve-routes',exported.template.R.length);

  console.log('PI V3 FINAL-FIVE SMOKE PASS');
})().catch(error=>{console.error(error);process.exit(1);});


const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const dbRoot=fs.mkdtempSync(path.join(os.tmpdir(),'new-eden-sage-pi-db-'));
try{
  const child=spawnSync(process.execPath,['-e',`const assert=require('node:assert/strict');const db=require('./dist-electron/database.js');const saved=db.savePlanetaryPlan({id:'pi-test',name:'Robotics test',savedAt:'2026-08-21T00:00:00.000Z',input:{characterId:'999',productTypeId:1,mode:'hybrid'}});assert.equal(saved.name,'Robotics test');assert.equal(db.listPlanetaryPlans().length,1);db.replacePlanetaryResourceObservations([{planetId:40000002,systemId:30000001,systemName:'Tanoo',planetTypeId:11,planetType:'Temperate',radiusKm:4820,resourceTypeId:2268,resourceName:'Aqueous Liquids',percent:67,confidence:.85,source:'synthetic',scope:'personal',characterId:'999',characterName:'PI Smoke',note:'synthetic'}]);const obs=db.listPlanetaryResourceObservations();assert.equal(obs.length,1);assert.equal(obs[0].percent,67);assert.equal(obs[0].systemId,30000001);assert.equal(obs[0].confidence,.85);assert.equal(obs[0].characterId,'999');const alerts=db.savePlanetaryAlertSettings({stockpileDays:3,optimizerMinIskPerDay:2500000,enabled:{'storage-95':true},overrides:{'character:999':{stockpileDays:1}}});assert.equal(alerts.stockpileDays,3);assert.equal(alerts.overrides['character:999'].stockpileDays,1);const tpl=db.savePlanetaryPlan({id:'pi-template',name:'Robotics v1',savedAt:'2026-08-21T00:00:00.000Z',input:{characterId:'999',productTypeId:2,mode:'full'},kind:'template',category:'Robotics',scope:'personal',layoutProfile:'throughput',designerLayout:{planetTypeId:11,nodes:[{id:'lp',typeId:1,x:0,y:0}],links:[]},eveTemplate:{Pln:11,P:[],L:[],R:[]}});assert.equal(tpl.kind,'template');assert.equal(db.listPlanetaryPlans().find(row=>row.id==='pi-template').category,'Robotics');const persistedTpl=db.listPlanetaryPlans().find(row=>row.id==='pi-template');assert.equal(persistedTpl.layoutProfile,'throughput');assert.equal(persistedTpl.designerLayout.planetTypeId,11);assert.equal(persistedTpl.eveTemplate.Pln,11);const dump=db.exportDatabaseData();assert.equal(dump.schemaVersion,3);assert.equal(dump.planetaryPlans.length,2);assert.equal(dump.planetaryResourceObservations.length,1);assert.equal(dump.planetaryAlertSettings.stockpileDays,3);db.deletePlanetaryPlan('pi-test');db.deletePlanetaryPlan('pi-template');assert.equal(db.listPlanetaryPlans().length,0);console.log('PI DATABASE PERSISTENCE V3 PASS');`],{cwd:path.resolve(__dirname,'../..'),env:{...process.env,NEW_EDEN_SAGE_USER_DATA:dbRoot},encoding:'utf8'});
  if(child.stdout)process.stdout.write(child.stdout);if(child.stderr)process.stderr.write(child.stderr);assert.equal(child.status,0,'isolated PI database regression failed');
}finally{fs.rmSync(dbRoot,{recursive:true,force:true});}
