const assert = require("node:assert/strict");
const fs = require("node:fs");
const main = fs.readFileSync("electron/main-task9.ts", "utf8");
const start = main.indexOf('ipcMain.handle("eve:login"');
const end = main.indexOf('ipcMain.handle("eve:refresh"', start);
assert.ok(start >= 0 && end > start, "must locate Add Character handler");
const login = main.slice(start, end);
assert.ok(login.includes("createConnectedCharacterBootstrapSnapshot"), "OAuth must preserve/create local character bootstrap");
assert.ok(login.includes("saveSnapshot(bootstrap)"), "saved character remains locally visible");
assert.ok(login.includes("missingScopes = EVE_SCOPES.filter"), "all current scopes are validated");
assert.ok(login.includes("await runMasterUpdate"), "Add Character must complete full private refresh");
assert.ok(login.indexOf("await runMasterUpdate") < login.indexOf("return {"), "full refresh must finish before success returns");
assert.ok(login.includes("Existing local data was preserved"), "sync failure must explicitly preserve last-known local data");
console.log("character add full-auth/full-sync regression checks passed");
