import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";

const root=path.resolve(".tmp-esi-private-runtime");
fs.rmSync(root,{recursive:true,force:true});
fs.mkdirSync(root,{recursive:true});
process.env.NEW_EDEN_SAGE_USER_DATA=root;
const key=Buffer.alloc(32,7).toString("base64");
const crypto=await import("../dist-electron/snapshot-crypto.js");
crypto.configureSnapshotEncryptionKey(key);
const database=await import("../dist-electron/database.js");
const cache=await import("../dist-electron/private-esi-cache.js");
cache.configurePrivateEsiEncryptionKey(key);
const secret="SAGE_PRIVATE_MAIL_SECRET_92";
database.saveSnapshot({characterId:"90000001",character:{name:"Runtime Test",corporation_id:1},updatedAt:new Date().toISOString(),extended:{mail:{headers:[{subject:secret}]}}});
const sqlitePath=path.join(root,"new-eden-sage.sqlite");
let db=new DatabaseSync(sqlitePath,{readOnly:true});
let raw=db.prepare("SELECT payload FROM character_snapshots WHERE character_id=?").get("90000001").payload;
assert.ok(String(raw).startsWith("sage-enc-v1:"),"snapshot row must be encrypted");
assert.ok(!String(raw).includes(secret),"snapshot ciphertext must not expose private mail plaintext");
const restored=database.getSnapshot("90000001");
assert.equal(restored.extended.mail.headers[0].subject,secret,"encrypted snapshot must decrypt through Sage database layer");
globalThis.fetch=async()=>new Response(JSON.stringify([{mail_id:1,subject:secret}]),{status:200,headers:{"cache-control":"max-age=0"}});
const first=await cache.privateEsiJson("90000001","/characters/90000001/mail/","test-token");
assert.equal(first.data[0].subject,secret);
db.close(); db=new DatabaseSync(sqlitePath,{readOnly:true});
const dataset=db.prepare("SELECT encrypted_payload,status FROM private_esi_datasets WHERE character_id=? AND dataset_id=?").get("90000001","character.mail.headers");
assert.ok(dataset?.encrypted_payload,"private dataset row must exist");
assert.ok(!String(dataset.encrypted_payload).includes(secret),"private dataset ciphertext must not expose mail plaintext");
globalThis.fetch=async()=>{throw new Error("simulated CCP outage")};
await new Promise(r=>setTimeout(r,5));
const stale=await cache.privateEsiJson("90000001","/characters/90000001/mail/","test-token");
assert.equal(stale.data[0].subject,secret,"last-known-good payload must survive endpoint failure");
assert.equal(stale.state,"stale","failed refresh with retained data must report stale state");
db.close();
console.log("private ESI runtime encryption/LKG checks passed");
