const assert=require("node:assert/strict");
const fs=require("node:fs");
const config=fs.readFileSync("electron/config.ts","utf8");
const db=fs.readFileSync("electron/database.ts","utf8");
const cache=fs.readFileSync("electron/private-esi-cache.ts","utf8");
const main=fs.readFileSync("electron/main-task9.ts","utf8");
const scopeManifest=fs.readFileSync("electron/esi-scope-manifest.ts","utf8");
const masterUpdate=fs.readFileSync("electron/master-update.ts","utf8");
const mcp=fs.readFileSync("electron/mcp-server.ts","utf8");
const launch=fs.readFileSync("electron/mcp-launch.ts","utf8");
assert.ok(config.includes("reauthorizationRequiredCharacterIds"));
assert.ok(main.includes("CURRENT_ESI_SCOPE_SCHEMA_VERSION"));
assert.ok(scopeManifest.includes("CURRENT_ESI_SCOPE_SCHEMA_VERSION = 2"), "this release must advance the ESI grant schema so every installation reauthorizes once even when intermediate releases were skipped");
assert.ok(main.includes("config.encryptedRefreshTokens = {}"), "migration invalidates old grants");
const migration=main.slice(main.indexOf("async function ensureEsiScopeSchemaMigration"),main.indexOf("async function planetaryCorporationContext"));
assert.ok(migration.includes("config.esiScopeSchemaVersion >= CURRENT_ESI_SCOPE_SCHEMA_VERSION"), "scope reset must be one-shot per schema version");
assert.ok(migration.includes("listSnapshots()"), "scope reset must include saved characters even when no refresh token survives");
assert.ok(migration.includes("Object.keys(config.encryptedRefreshTokens)"), "scope reset must include currently connected characters");
assert.ok(migration.includes("Object.keys(config.eveAuthorizations)"), "scope reset must include characters represented only by authorization metadata");
assert.ok(masterUpdate.includes("reauthorizationRequiredCharacterIds = latestConfig.reauthorizationRequiredCharacterIds.filter"), "successful full private sync must clear only that character's one-time reauthorization requirement");
assert.ok(!migration.includes("clearCharacterSnapshots"), "scope migration must not delete snapshots");
assert.ok(cache.includes("aes-256-gcm"), "private endpoint payloads must use authenticated encryption");
assert.ok(db.includes("encryptSnapshotPayload(normalized)"), "complete snapshots must be encrypted at rest");
assert.ok(db.includes("migratePlaintextSnapshotsToEncrypted"), "legacy plaintext snapshots must be migrated");
assert.ok(db.includes("encryptedCharacterSnapshots"), "full backup must handle encrypted snapshot payloads intentionally");
assert.ok(cache.includes("stateForFailure") && cache.includes("hasLastKnownGood"), "last-known-good state must survive refresh failure");
assert.ok(cache.includes('"permission-missing"') && cache.includes('"role-missing"') && cache.includes('"rate-limited"'), "failure states must remain distinct");
assert.ok(mcp.includes("getDatabaseSnapshot") && mcp.includes("listDatabaseSnapshots"), "MCP must use encrypted snapshot-aware database access");
assert.ok(launch.includes("ELECTRON_RUN_AS_NODE") && launch.includes("NEW_EDEN_SAGE_USER_DATA"), "MCP must retain reliable Node stdio with the Sage data-root context");
const dpapi=fs.readFileSync("electron/windows-dpapi.ts","utf8");
const mcpKey=fs.readFileSync("electron/mcp-private-key.ts","utf8");
assert.ok(dpapi.includes("ProtectedData") && dpapi.includes("DataProtectionScope]::CurrentUser"), "MCP compatibility key must remain Windows CurrentUser-DPAPI protected");
assert.ok(mcpKey.includes("unprotectCurrentUserDpapi"), "MCP must unwrap the protected DEK without storing plaintext");
console.log("ESI scope migration, encryption and persistence regression checks passed");
