const assert = require("node:assert/strict");
const fs = require("node:fs");
const main = fs.readFileSync("electron/main-task9.ts", "utf8");
const app = fs.readFileSync("src/App.tsx", "utf8");
const hr = fs.readFileSync("src/CorporationHr.tsx", "utf8");
const service = fs.readFileSync("electron/hr-service.ts", "utf8");
const start = main.indexOf('ipcMain.handle("eve:login"');
const end = main.indexOf('ipcMain.handle("eve:refresh"', start);
assert.ok(start >= 0 && end > start, "must expose Add Character auth handler");
const handler = main.slice(start, end);
assert.ok(handler.includes("missingScopes = EVE_SCOPES.filter"), "login must validate complete current scope manifest");
assert.ok(handler.indexOf("missingScopes = EVE_SCOPES.filter") < handler.indexOf("encryptedRefreshTokens[login.characterId] = encrypt(login.refreshToken)"), "scope validation must precede credential replacement");
assert.ok(handler.includes("runMasterUpdate"), "login must immediately run full private sync");
assert.ok(handler.includes("mailHeadersCaptured"), "login result must report mail coverage");
assert.ok(main.includes("ensureEsiScopeSchemaMigration"), "scope-schema migration must exist");
assert.ok(main.includes("snapshotsPreserved"), "scope migration must preserve local snapshots");
assert.ok(app.includes("RE-AUTH REQUIRED"), "Settings must visibly show forced reauthorization state");
assert.ok(app.includes("Add Character"), "Settings must direct saved characters through normal Add Character flow");
assert.ok(service.includes("STALE BUT USABLE"), "HR must distinguish stale usable private data");
assert.ok(service.includes("OAuth scope missing"), "HR must distinguish missing OAuth scope");
assert.ok(service.includes("EVE corporation role missing"), "HR must distinguish missing corporation role");
assert.ok(hr.includes("function HrSectionContent"), "HR dossier must use structured category renderers");
assert.ok(hr.includes("corp-hr-human-table"), "HR dossier must render scan-friendly tables");
assert.ok(hr.includes("Message contents"), "HR mail drill-down must expose readable message bodies");
assert.ok(hr.includes("Raw ESI payload"), "raw evidence remains optional");
console.log("HR dossier and forced ESI reauthorization regression checks passed");
