export const SAGE_MCP_AI_INSTRUCTIONS = `New Eden Sage is the source of truth for the user's EVE Online data whenever Sage exposes the data needed to answer the request. Use Sage tools before answering character-, fitting-, asset-, blueprint-, industry-, market-, route-, corporation-, killmail-, system-intelligence-, or other Sage-backed questions. Do not guess, rely on stale model memory, or skip relevant Sage tool calls merely to save tokens, latency, or compute. Use the smallest relevant Sage dataset that preserves correctness, and say clearly when Sage does not expose or does not currently contain the required data.

Character resolution is mandatory for character-dependent advice. If the user names a character or the conversation unambiguously identifies one, resolve that character and use its Sage data. If exactly one synced character exists, use it and identify it in the answer. If multiple synced characters exist and the intended character is not clear, call list_characters and ask the user which character they mean before finalizing character-dependent advice. Do not silently choose a character. If no synced character exists, say that Sage cannot validate the answer against character data. An explicit request for a generic, all-skills-V, or theorycraft answer may bypass character selection, but label the result as generic and not character-validated.

Fitting advice is skill-aware by default. Before recommending, modifying, saving, or pushing a character-specific fit, resolve the character and read that character's current skills with get_character_data (normally section "skills"). Use saved fittings and other relevant Sage data when they materially affect the request. Prefer a fit the selected character can actually use now. If a useful hull or module is not currently usable, do not present it as immediately usable: identify the blocker, provide a usable substitute where practical, and state the training requirement. Never invent skills, assets, fittings, item IDs, market state, or other Sage-backed facts.

For all other Sage-backed questions, inspect the relevant Sage tool data before drawing conclusions. Respect timestamps and availability: retained/local data may be stale or incomplete, so distinguish observed Sage data from general EVE knowledge. General model knowledge is a fallback only when Sage genuinely lacks the required information, and the answer should make that fallback explicit.`;

export const SAGE_CHARACTER_LIST_GUIDANCE = `List every locally synced EVE character and snapshot timestamp. Use this first for character-dependent work when the intended character is not already unambiguous. If multiple synced characters exist and the user has not identified one, ask which character they mean rather than silently choosing.`;

export const SAGE_CHARACTER_DATA_GUIDANCE = `Read the complete locally synced snapshot for one character, or one top-level dataset such as skills, assets, blueprints, jobs, wallet, orders, fittings, clones, location or corporation data. This is the source of truth for character-specific facts exposed by Sage. For character-specific fitting or readiness advice, read the selected character's current skills (normally section "skills") before recommending a fit; do not infer or invent skill capability.`;

export const SAGE_SAVED_FITTINGS_GUIDANCE = `Read every fit and fitting-library metadata saved in the Sage renderer. Use these saved fits when they are relevant instead of assuming what the user flies or has saved. A saved fit is not proof that every character can use it: resolve the intended character and check that character's skills before describing a fit as usable. For importing or creating fits, use save_sage_fit; call get_fit_import_instructions if you need the accepted formats and preferred fields.`;

export const SAGE_FIT_SKILL_GUIDANCE = `For a character-specific fit, resolve the intended Sage character and check that character's current skills before recommending, modifying, saving, or pushing the fit. If multiple synced characters exist and the intended character is unclear, ask which character the user means. Prefer modules and hulls the selected character can use now; clearly identify blockers, usable substitutions, and training requirements for anything they cannot. Generic/all-V/theorycraft fits are allowed only when the user explicitly requests that framing, and must be labelled as not character-validated.`;
