const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..", "..");
const read = (name) => fs.readFileSync(path.join(root, name), "utf8");

const shared = read("electron/shared-market-data.ts");
assert.match(shared, /\/latest-complete/, "desktop should use latest-complete for read-only public reconciliation");
assert.doesNotMatch(shared, /fetch[^\n]*ensure-current|request\([^\n]*ensure-current/, "desktop must not make normal ensure-current HTTP requests");
assert.match(shared, /manifestsIdentical/, "unchanged generation should compare metadata");
assert.match(shared, /if \(identical\)[\s\S]*?changed: \[\]/, "unchanged generation should return without downloads");
assert.match(shared, /globalGenerationCache/);
assert.match(shared, /regionalGenerationCache/);
assert.match(shared, /tradeGenerationCache/);
assert.match(shared, /shortageGenerationCache/);
assert.match(shared, /publicSharedGenerationCache/);
assert.match(shared, /public-shared/);
assert.match(shared, /public-contracts/);
assert.match(shared, /contractGenerationCache/);
assert.match(shared, /loadSharedPublicContractsDataset/);
assert.match(shared, /startSharedPublicDataListener/);
assert.match(shared, /checkSharedMarketDataAvailability/);
assert.match(shared, /public-data-ready/);
const listenerStart = shared.indexOf("export function startSharedPublicDataListener");
assert.ok(listenerStart >= 0, "shared public listener should remain identifiable");
const listenerBody = shared.slice(listenerStart);
assert.doesNotMatch(listenerBody, /await ensureCurrentSharedMarketData\(/, "public-data-ready events must signal availability without auto-installing artifacts");
assert.doesNotMatch(shared, /artifact\.version !== generation/, "artifact versions must be dependency-specific rather than forced to the outer publication generation");
assert.match(shared, /shared_market\.latest_manifest_ms/);
assert.match(shared, /shared_market\.generation_compare_ms/);
assert.match(shared, /shared_market\.promotion_ms/);
assert.match(shared, /shared_market\.total_ms/);

const master = read("electron/master-update.ts");
assert.match(master, /marketDownloadWorkers:\s*0/);
assert.match(master, /publicMarketSource: "shared-server"/);
assert.match(master, /privateDataOnly: true/);
assert.doesNotMatch(master, /ensureCurrentSharedMarketData|master-derived-worker|stageStaticDataRefreshLowImpact|buildFullMarketAnalysisIndexParallel|buildRegionalMarketAggregateIndex/);
assert.match(master, /character_refresh\.per_character/);
assert.match(master, /character_refresh\.total/);

const main = read("electron/main-task9.ts");
assert.match(main, /Public market data is server-managed/);
assert.match(main, /public-data:check-availability/);
assert.match(main, /PUBLIC_RECONCILE_INTERVAL_MS = 60 \* 60 \* 1000/);
assert.doesNotMatch(main.slice(main.indexOf('ipcMain.handle("market:pull"'), main.indexOf("createWindow();", main.indexOf('ipcMain.handle("market:pull"'))), /pullMarketRegion|beginRawMarketSnapshot|saveRawMarketRegion|pullRegionContracts/);
assert.match(main, /input\?\.mode !== "contracts"/);
assert.match(main, /loadSharedPublicContractsDataset/);
assert.match(main, /loadSharedMarketBrowserSummaries/);
assert.match(main, /loadSharedMarketBrowserRegion/);
assert.doesNotMatch(main, /listRegions\(\)/);

const trade = read("electron/full-market-trade.ts");
const tradeStart = trade.indexOf("export async function findFullMarketTrades(");
const tradeEnd = trade.indexOf("\nasync function mapLimited<", tradeStart);
const tradeBody = trade.slice(tradeStart, tradeEnd);
assert.match(tradeBody, /loadSharedPreparedTradeDataset/);
assert.doesNotMatch(tradeBody, /buildCandidatesInParallel|universeRoute|\b30_000\b|\b8_000\b/, "desktop trade path must not generate public candidates/routes");

const shortage = read("electron/regional-shortage.ts");
const shortageStart = shortage.indexOf("export async function findRegionalShortages(");
const shortageBody = shortage.slice(shortageStart);
assert.match(shortageBody, /loadSharedPreparedShortageDataset/);
assert.doesNotMatch(shortageBody, /buildFullMarketAnalysisIndex|candidateBufferLimit|retainStrongestCandidates/, "desktop shortage path must not rescan the public market");

const raw = read("electron/raw-market-analysis.ts");
assert.match(raw, /Desktop public-market reconstruction is disabled/);
assert.match(raw, /Desktop full-market shard computation is disabled/);
const regional = read("electron/regional-market-index.ts");
assert.match(regional, /Desktop regional reconstruction is disabled/);
assert.match(regional, /rowsByType: Map<number, RegionalMarketAggregateRow\[\]>/);

const industrial = read("electron/industrial-preparation.ts");
assert.match(industrial, /typeIds: \[Number\(product\.typeId\)\]/, "Industrial lookup should use exact prepared type IDs");
const industrialEngine = read("electron/industrial-engine.ts");
assert.match(industrialEngine, /loadSharedFullMarketAnalysisIndex/);
assert.match(industrialEngine, /loadSharedPublicSource/);
assert.doesNotMatch(industrialEngine, /fetch\("https:\/\/esi\.evetech\.net\/(?:markets\/prices|industry\/systems)/);

const pve = read("electron/pve-location-intelligence.ts");
assert.match(pve, /loadSharedPublicSource/);
assert.doesNotMatch(pve, /fetchJson<LivePveData\["(?:incursions|kills|jumps)"\]>/);
const systems = read("electron/system-intelligence.ts");
assert.match(systems, /loadSharedPublicSource/);
const home = read("electron/corporation-home-finder.ts");
assert.match(home, /loadSharedPublicSource/);
const nav = read("electron/navigation-route-intelligence.ts");
assert.match(nav, /loadSharedPublicSource/);
assert.match(nav, /sovereignty-systems/);
assert.doesNotMatch(nav, /sovereignty-map|sovereignty\/map/);

const modal = read("tools/modal/sage_market_benchmark.py");
const worker = read("tools/modal/public_data_worker.mjs");
assert.match(modal, /@web\.get\("\/latest-complete"\)/);
const latestStart = modal.indexOf('    @web.get("/latest-complete")');
const latestEnd = modal.indexOf('    @web.get("/ensure-current")', latestStart);
const latestBody = modal.slice(latestStart, latestEnd);
assert.doesNotMatch(latestBody, /refresh_market_if_stale|benchmark_market_pipeline/, "latest-complete must be read-only");
assert.match(modal, /schedule=modal\.Period\(minutes=5\)/);
assert.match(modal, /new-eden-sage-public-history/);
assert.match(modal, /@web\.get\("\/events"\)/);
assert.match(modal, /public-data-ready/);
assert.match(modal, /generation_manifest_path/, "artifact serving should validate the requested generation's manifest");

assert.match(worker, /NEW_EDEN_SAGE_PUBLIC_HISTORY_RETENTION_DAYS \|\| 120/);
assert.match(worker, /cache-control/);
assert.match(worker, /expires/);
assert.match(worker, /If-None-Match/);
assert.match(worker, /If-Modified-Since/);
assert.match(worker, /retry-after/);
assert.match(worker, /x-esi-error-limit-reset/);
assert.match(worker, /response\.status === 304/);
assert.match(worker, /kind: 'checkpoint'/);
assert.match(worker, /kind: 'delta'/);
assert.match(worker, /removedOrderIds/);
assert.match(worker, /public-contracts-v1\.json\.gz/);
assert.match(worker, /refreshPublicContracts/);
assert.match(worker, /CONTRACT_DETAIL_BUDGET/);
assert.match(worker, /if \(!buffer\.byteLength\) return retained/);
assert.match(worker, /items = JSON\.parse\(buffer\.toString\('utf8'\)\)[\s\S]*?catch \{[\s\S]*?return retained/, "malformed contract detail enrichment must stay pending rather than abort publication");
assert.match(worker, /key: 'sovereignty-systems', url: '\/sovereignty\/systems\/'/);
assert.doesNotMatch(worker, /sovereignty-map|sovereignty\/map/);
assert.match(worker, /const sourceDigest = sha256\(Buffer\.from\(JSON\.stringify\(\{ contractSourceDigest, marketPriceDigest \}\)\)\)/);
assert.match(worker, /if \(!sourceChanged && previous\)[\s\S]*?changed: false/, "contract enrichment progress alone must not publish a new outer generation");
assert.match(worker, /removedContractIds/);
assert.match(worker, /HISTORY_PARTITION_INDEX_ROOT/);
assert.match(worker, /ensureHistoryMetadata/);
assert.match(worker, /reconcileHistoryPartitionIndexes/);
assert.match(worker, /historyPartitionsPruned/);
const pruneStart = worker.indexOf("async function pruneHistory()");
const statsStart = worker.indexOf("async function historyStats()", pruneStart);
const mainStart = worker.indexOf("async function main()", statsStart);
assert.ok(pruneStart >= 0 && statsStart > pruneStart && mainStart > statsStart);
assert.doesNotMatch(worker.slice(pruneStart, statsStart), /fs\.stat|async function walk/, "normal retention pruning must delete indexed date partitions without scanning history files");
assert.doesNotMatch(worker.slice(statsStart, mainStart), /fs\.stat|async function walk/, "normal history stats must aggregate partition metadata rather than scan history files");
assert.match(worker, /if \(!materialChanged\)/);
assert.match(worker, /market-global-v1\.json\.gz/);
assert.match(worker, /market-regional-v1\.jsonl\.gz/);
assert.match(worker, /market-trades-v1\.json\.gz/);
assert.match(worker, /market-shortages-v1\.json\.gz/);
assert.match(worker, /public-shared-v1\.json\.gz/);
assert.match(worker, /public-contracts-v1\.json\.gz/);

const contractUi = read("src/MarketContracts.tsx");
assert.doesNotMatch(contractUi, /Starting EVE-wide public contract scan/);
assert.match(contractUi, /server-prepared public contracts/i);

const app = read("src/App.tsx");
assert.doesNotMatch(app, /take up to 5 minutes/i);
assert.doesNotMatch(app, /Sync All|Syncing all/i);
assert.match(app, /REFRESH PRIVATE DATA/);
assert.doesNotMatch(app, /Pull region|Ready to pull public ESI market data/);
assert.match(app, /Reload installed data/);
assert.doesNotMatch(app, /install automatically/i);

console.log("Server-first public data and rolling history architecture tests passed.");
