import { useEffect, useMemo, useRef, useState } from "react";
import { OperationFitPreview } from "./OperationFitPreview";
import "./corp-ops-polish.css";
import "./corp-ops-finish.css";

type CorpRecord={characterId:string;characterName:string;corporationId:number;name:string;snapshot:any;data:any};
type Ship={typeId:number;name:string;groupName:string};
type OpRole={id:string;label:string;hullName:string;hullTypeId:number;count:number;notes:string;x:number;y:number};
type OpApplication={id:string;characterId:number;characterName:string;roleId:string;fitName:string;fitText:string;hullName:string;status:"pending"|"approved"|"denied";submittedAt:string;message?:string;decidedAt?:string;decidedBy?:{characterId:number;characterName:string}};
type DiscordRole={id:string;name:string;position:number;color:number;managed:boolean;mentionable:boolean};
type DiscordMember={id:string;username:string;globalName:string|null;displayName:string;roleIds:string[]};
type DiscordStructure={guildId:string;guildName:string;roles:DiscordRole[];members:DiscordMember[];membersAvailable:boolean;membersTruncated:boolean};
type OpPayload={schema:"new-eden-sage.operation.v1";operationId:string;title:string;operationType:string;description:string;formupSystem:string;startsAt:string;fitCheckEnabled:boolean;approvalRequired?:boolean;discordAnnouncementEnabled?:boolean;discordNotifyRoleIds?:string[];discordNotifyUserIds?:string[];status:"forming"|"active"|"complete"|"cancelled";cancellationMessage?:string;cancelledAt?:string;cancelledBy?:{characterId:number;characterName:string};operationOwner?:{characterId:number;characterName:string};notificationLeaderCharacterIds?:number[];createdBy:{characterId:number;characterName:string};roles:OpRole[];applications:OpApplication[];createdAt:string;updatedAt:string};
type OpEntry={summary:{id:string;current_version:number;updated_at:string;published_at?:string};payload:OpPayload};
type Workspace={workspace_id:string;corporation_id:number;corporation_name:string;character_id:number;character_name:string;can_manage_fleet_ops?:boolean;can_approve_fleet_ops?:boolean;can_configure_permissions?:boolean;roles:string[];titles:string[];member_access:"active"};
type OpMode="command"|"join";
const OP_TYPES=["PvP Roam","Structure Defense","Structure Attack","Mining Operation","PvE Fleet","Hauling / Logistics","Wormhole Operation","Training","Other"];
const id=()=>crypto.randomUUID();
const assetUrl=(typeId:number)=>typeId>0?`sage-asset://type/${typeId}/render?size=128`:"";
function blankRole(label="DPS",x=50,y=50):OpRole{return{id:id(),label,hullName:"",hullTypeId:0,count:1,notes:"",x,y};}
function blankPayload(characterId:number,characterName:string):OpPayload{const now=new Date().toISOString();return{schema:"new-eden-sage.operation.v1",operationId:id(),title:"",operationType:"PvP Roam",description:"",formupSystem:"",startsAt:"",fitCheckEnabled:true,approvalRequired:true,discordAnnouncementEnabled:true,discordNotifyRoleIds:[],discordNotifyUserIds:[],status:"forming",createdBy:{characterId,characterName},operationOwner:{characterId,characterName},notificationLeaderCharacterIds:[],roles:[blankRole("DPS",36,46),blankRole("Logistics",64,46),blankRole("Tackle",50,70)],applications:[],createdAt:now,updatedAt:now};}

function TacticalBoard({payload,editable,onChange}:{payload:OpPayload;editable:boolean;onChange?(next:OpPayload):void}){
  const ref=useRef<HTMLDivElement|null>(null);
  const appsByRole=useMemo(()=>{const map=new Map<string,OpApplication[]>();for(const app of payload.applications.filter(a=>a.status==="approved")){const rows=map.get(app.roleId)??[];rows.push(app);map.set(app.roleId,rows);}return map;},[payload.applications]);
  function dragEnd(event:React.DragEvent,role:OpRole){if(!editable||!ref.current||!onChange)return;const rect=ref.current.getBoundingClientRect();const x=Math.max(8,Math.min(92,(event.clientX-rect.left)/rect.width*100));const y=Math.max(12,Math.min(88,(event.clientY-rect.top)/rect.height*100));onChange({...payload,roles:payload.roles.map(r=>r.id===role.id?{...r,x,y}:r),updatedAt:new Date().toISOString()});}
  return <div className="op-space-map" ref={ref}><div className="op-space-grid"/><div className="op-map-anchor"><span>OP</span><strong>{payload.title||"Operation"}</strong><small>{payload.formupSystem||"Form-up TBD"}</small></div>
    {payload.roles.map(role=>{const approved=appsByRole.get(role.id)??[];const filled=approved.length>=role.count;return <div key={role.id} draggable={editable} onDragEnd={e=>dragEnd(e,role)} className={`op-role-node ${filled?"filled":""} ${editable?"draggable":""}`} style={{left:`${role.x}%`,top:`${role.y}%`}}>
      {role.hullTypeId>0?<img src={assetUrl(role.hullTypeId)} alt=""/>:<div className="op-role-placeholder">SHIP</div>}<strong>{role.label}</strong><span>{role.hullName||"Any suitable hull"}</span><small>{approved.length}/{role.count} approved</small>
      {approved.map(app=><em key={app.id} className="op-approved-ship">âœ“ {app.characterName}{app.hullName?` Â· ${app.hullName}`:""}</em>)}
    </div>;})}
    {!payload.roles.length&&<div className="op-map-empty">Add roles to place ships on the tactical board.</div>}
  </div>;
}

function OperationList({ops,selectedId,onSelect,title}:{ops:OpEntry[];selectedId:string;onSelect:(id:string)=>void;title:string}){
  return <aside className="op-list op-panel"><div className="op-list-head"><strong>{title}</strong><small>{ops.length} broadcast operation{ops.length===1?"":"s"}</small></div>
    <div className="op-list-scroll">{ops.map(op=>{const approved=op.payload.applications.filter(a=>a.status==="approved").length;const pending=op.payload.applications.filter(a=>a.status==="pending").length;return <button key={op.summary.id} className={`${selectedId===op.summary.id?"active":""} ${op.payload.status==="cancelled"?"cancelled":""}`.trim()} onClick={()=>onSelect(op.summary.id)}><strong>{op.payload.title||"Untitled operation"}</strong><span>{op.payload.operationType}</span><small>{op.payload.status} Â· {approved} approved Â· {pending} pending</small></button>;})}
      {!ops.length&&<div className="op-empty-state"><strong>No broadcasts yet</strong><span>Published corporation operations will appear here.</span></div>}
    </div>
  </aside>;
}

export function CorporationOpPlanner({corporation}:{corporation:CorpRecord;snapshots:any[]}){
  const [workspace,setWorkspace]=useState<Workspace|null>(null);const [ops,setOps]=useState<OpEntry[]>([]);const [selectedId,setSelectedId]=useState("");const [busy,setBusy]=useState(false);const [status,setStatus]=useState("Connecting to the corporation operation workspace...");const [mode,setMode]=useState<OpMode>("join");
  const [ships,setShips]=useState<Ship[]>([]);const [discordStructure,setDiscordStructure]=useState<DiscordStructure|null>(null);const [discordMemberQuery,setDiscordMemberQuery]=useState("");const [creating,setCreating]=useState(false);const [draft,setDraft]=useState<OpPayload|null>(null);const [editing,setEditing]=useState<OpPayload|null>(null);const [applyRoleId,setApplyRoleId]=useState("");const [fitName,setFitName]=useState("");const [fitText,setFitText]=useState("");const [hullName,setHullName]=useState("");const [decisionMessages,setDecisionMessages]=useState<Record<string,string>>({});const [viewFitApp,setViewFitApp]=useState<OpApplication|null>(null);const [cancelOpen,setCancelOpen]=useState(false);const [cancelMessage,setCancelMessage]=useState("");
  const selected=ops.find(op=>op.summary.id===selectedId)??ops[0]??null;const activePayload=editing&&selected?editing:selected?.payload??null;const characterId=Number(corporation.characterId);const canManage=workspace?.can_manage_fleet_ops===true;const canApprove=workspace?.can_approve_fleet_ops===true;const canCommand=canManage||canApprove;const canJoin=workspace?.member_access==="active";

  async function list(ws=workspace){if(!ws)return;const rows=await window.sage.listCorporationOperations({workspaceId:ws.workspace_id}) as OpEntry[];const activeRows=rows.filter(row=>row.payload.status!=="cancelled");setOps(activeRows);setSelectedId(current=>current&&activeRows.some(r=>r.summary.id===current)?current:activeRows[0]?.summary.id??"");}
  async function load(){setBusy(true);setWorkspace(null);setOps([]);setSelectedId("");setCreating(false);setDraft(null);setEditing(null);setDiscordStructure(null);setMode("join");try{const ws=await window.sage.getCorporationOpsWorkspace(corporation.characterId) as Workspace;setWorkspace(ws);if(ws.can_manage_fleet_ops||ws.can_approve_fleet_ops)setMode("command");if(ws.can_manage_fleet_ops){try{const discord=await window.sage.getCorporationDiscordServerStructure(corporation.characterId) as DiscordStructure;setDiscordStructure(discord);}catch{setDiscordStructure(null);}}await list(ws);setStatus(ws.can_manage_fleet_ops?"Command authority verified. You can create, broadcast and manage corporation operations.":"Verified corporation member. Join Ops is available for role requests.");}catch(error){setStatus(error instanceof Error?error.message:"Corporation operation workspace is unavailable.");}finally{setBusy(false);}}
  useEffect(()=>{void load();void window.sage.listShips().then(rows=>setShips(rows.map(r=>({typeId:r.typeId,name:r.name,groupName:r.groupName}))));},[corporation.characterId]);
  useEffect(()=>{if(!workspace)return;const timer=window.setInterval(()=>void list(workspace).catch(()=>undefined),20000);return()=>window.clearInterval(timer);},[workspace?.workspace_id]);
  useEffect(()=>{setApplyRoleId("");setFitName("");setFitText("");setHullName("");setViewFitApp(null);setCancelOpen(false);setCancelMessage("");},[selectedId]);

  function startCreate(){if(!workspace||!canManage)return;setMode("command");setCreating(true);setEditing(null);setDraft(blankPayload(Number(workspace.character_id),workspace.character_name));}
  function updateRole(payload:OpPayload,roleId:string,patch:Partial<OpRole>,setter:(p:OpPayload)=>void){setter({...payload,roles:payload.roles.map(role=>role.id===roleId?{...role,...patch}:role),updatedAt:new Date().toISOString()});}
  function setRoleHull(payload:OpPayload,roleId:string,name:string,setter:(p:OpPayload)=>void){const match=ships.find(ship=>ship.name.toLowerCase()===name.trim().toLowerCase());updateRole(payload,roleId,{hullName:name,hullTypeId:match?.typeId??0},setter);}
  async function broadcast(){if(!draft||!workspace||!canManage)return;if(!draft.title.trim()||!draft.roles.length){setStatus("Give the operation a title and at least one role before broadcasting.");return;}setBusy(true);try{const payload={...draft,discordNotifyRoleIds:draft.discordNotifyRoleIds??[],discordNotifyUserIds:draft.discordNotifyUserIds??[],updatedAt:new Date().toISOString()};const result=await window.sage.publishCorporationOperation({characterId:corporation.characterId,payload});setWorkspace(result.workspace as Workspace);setCreating(false);setDraft(null);let message="Operation broadcast to verified corporation members in Sage.";if(payload.discordAnnouncementEnabled!==false){try{await window.sage.announceCorporationOperationDiscord({characterId:corporation.characterId,workspaceId:(result.workspace as Workspace).workspace_id,objectId:result.id});message="Operation broadcast in Sage and announced to Discord.";}catch(error){message=`Operation broadcast in Sage. Discord announcement was not sent: ${error instanceof Error?error.message:"Discord is not ready."}`;}}setStatus(message);await list(result.workspace as Workspace);setSelectedId(result.id);}catch(error){setStatus(error instanceof Error?error.message:"Operation broadcast failed.");}finally{setBusy(false);}}
  async function saveEdit(){if(!editing||!selected||!workspace||!canManage)return;setBusy(true);try{const now=new Date().toISOString();const normalized:OpPayload=editing.approvalRequired===false?{...editing,discordNotifyRoleIds:editing.discordNotifyRoleIds??[],discordNotifyUserIds:editing.discordNotifyUserIds??[],fitCheckEnabled:false,applications:editing.applications.map(app=>app.status==="pending"?{...app,status:"approved" as const,decidedAt:now,decidedBy:editing.createdBy}:app),updatedAt:now}:{...editing,discordNotifyRoleIds:editing.discordNotifyRoleIds??[],discordNotifyUserIds:editing.discordNotifyUserIds??[],updatedAt:now};await window.sage.updateCorporationOperation({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id,payload:normalized,expectedVersion:selected.summary.current_version});setEditing(null);let message=normalized.approvalRequired===false?"Operation updated. Pending and future role requests are auto-approved.":"Operation details and tactical layout updated.";if(normalized.discordAnnouncementEnabled!==false){try{await window.sage.announceCorporationOperationDiscord({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id});message+=" Discord announcement sent.";}catch(error){message+=` Discord announcement was not sent: ${error instanceof Error?error.message:"Discord is not ready."}`;}}setStatus(message);await list();}catch(error){setStatus(error instanceof Error?error.message:"Operation update failed.");}finally{setBusy(false);}}
  async function apply(){if(!selected||!workspace||!applyRoleId||!canJoin||selected.payload.status==="cancelled")return;const automatic=selected.payload.approvalRequired===false;setBusy(true);try{await window.sage.applyCorporationOperationRole({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id,roleId:applyRoleId,fitName,fitText,hullName});setStatus(automatic?"Role request approved automatically and added to the formation.":"Role request sent. You can track its state in Join Ops.");setApplyRoleId("");setFitName("");setFitText("");setHullName("");await list();}catch(error){setStatus(error instanceof Error?error.message:"Role request failed.");}finally{setBusy(false);}}
  async function decide(app:OpApplication,decision:"approved"|"denied"){if(!selected||!workspace||!canApprove)return;setBusy(true);try{await window.sage.decideCorporationOperationApplication({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id,applicationId:app.id,decision,message:decisionMessages[app.id]??""});setStatus(decision==="approved"?`${app.characterName} approved for the operation.`:`${app.characterName} denied${decisionMessages[app.id]?" with a message":""}.`);await list();}catch(error){setStatus(error instanceof Error?error.message:"Application decision failed.");}finally{setBusy(false);}}
  async function announceSelected(){if(!selected||!workspace||!canManage||selected.payload.status==="cancelled")return;setBusy(true);try{await window.sage.announceCorporationOperationDiscord({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id});setStatus("Operation announced to Discord using the current stored operation details and mention policy.");}catch(error){setStatus(error instanceof Error?error.message:"Discord operation announcement failed.");}finally{setBusy(false);}}
  async function takeOwnership(){if(!selected||!workspace||!canManage)return;setBusy(true);try{await window.sage.takeCorporationOperationOwnership({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id});setStatus("You now own this operation.");await list();}catch(error){setStatus(error instanceof Error?error.message:"Operation ownership change failed.");}finally{setBusy(false);}}
  async function toggleMyNotifications(){if(!selected||!workspace||!canManage)return;const subscribed=(selected.payload.notificationLeaderCharacterIds??[]).includes(characterId);setBusy(true);try{await window.sage.setCorporationOperationApplicationNotifications({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:selected.summary.id,enabled:!subscribed});setStatus(subscribed?"Removed you from this operation's role-request notifications.":"Added you to this operation's role-request notifications.");await list();}catch(error){setStatus(error instanceof Error?error.message:"Operation notification setting failed.");}finally{setBusy(false);}}
  async function cancelSelected(){if(!selected||!workspace||!canManage||selected.payload.status==="cancelled"||selected.payload.status==="complete")return;const message=cancelMessage.trim();const cancelledId=selected.summary.id;setBusy(true);try{const result=await window.sage.cancelCorporationOperation({characterId:corporation.characterId,workspaceId:workspace.workspace_id,objectId:cancelledId,message});setCancelOpen(false);setCancelMessage("");setEditing(null);setApplyRoleId("");setOps(current=>current.filter(op=>op.summary.id!==cancelledId));setSelectedId("");const discordParts:string[]=[];if(result.discordDeleted)discordParts.push("old Discord op post removed");if(result.discordCancellationSent)discordParts.push("cancellation notice sent");if(result.discordCleanupWarning)discordParts.push(`Discord cleanup warning: ${result.discordCleanupWarning}`);if(result.discordCancellationWarning)discordParts.push(`Discord cancellation warning: ${result.discordCancellationWarning}`);setStatus(`Operation cancelled and removed from active Ops.${discordParts.length?` ${discordParts.join(" · ")}.`:""}`);await list(workspace);}catch(error){setStatus(error instanceof Error?error.message:"Operation cancellation failed.");}finally{setBusy(false);}}

  const myApp=selected?.payload.applications.find(app=>app.characterId===characterId);const pending=selected?.payload.applications.filter(app=>app.status==="pending")??[];const editor=creating?draft:editing;const editorSetter=creating?setDraft:setEditing;
  const roleFor=(payload:OpPayload|undefined|null,roleId:string)=>payload?.roles.find(role=>role.id===roleId);

  function Editor(){if(!editor)return null;return <section className="op-editor op-panel">
    <div className="op-editor-heading"><div><p className="eyebrow">{creating?"NEW BROADCAST":"EDIT OPERATION"}</p><h3>{creating?"Build the operation":"Update command plan"}</h3><p>Define the objective, demand and tactical layout in one contained command workspace.</p></div><span>{editor.roles.length} role groups</span></div>
    <div className="op-editor-grid">
      <div className="op-editor-stack">
        <div className="op-editor-form op-panel-inner"><label><span>Operation title</span><input value={editor.title} onChange={e=>editorSetter({...editor,title:e.target.value})}/></label><label><span>Type</span><select value={editor.operationType} onChange={e=>editorSetter({...editor,operationType:e.target.value})}>{OP_TYPES.map(type=><option key={type}>{type}</option>)}</select></label><label><span>Form-up / system</span><input value={editor.formupSystem} onChange={e=>editorSetter({...editor,formupSystem:e.target.value})}/></label><label><span>Start time</span><input type="datetime-local" value={editor.startsAt} onChange={e=>editorSetter({...editor,startsAt:e.target.value})}/></label><label className="op-editor-wide"><span>Orders / description</span><textarea value={editor.description} onChange={e=>editorSetter({...editor,description:e.target.value})}/></label><div className="op-approval-policy"><label className="op-fit-toggle"><input type="checkbox" checked={editor.approvalRequired!==false} onChange={e=>editorSetter({...editor,approvalRequired:e.target.checked,fitCheckEnabled:e.target.checked?editor.fitCheckEnabled:false})}/><span><strong>Require leadership approval</strong><small>Off = valid role requests are approved immediately.</small></span></label><label className="op-fit-toggle"><input type="checkbox" checked={editor.fitCheckEnabled} disabled={editor.approvalRequired===false} onChange={e=>editorSetter({...editor,fitCheckEnabled:e.target.checked})}/><span><strong>Require fit review</strong><small>Members must submit a fit before an approver can accept the role.</small></span></label></div></div>
        <div className="op-discord-broadcast op-panel-inner"><div className="op-discord-broadcast-head"><div><p className="eyebrow">DISCORD ANNOUNCEMENT</p><strong>Notify the corporation server</strong><small>SageBot posts the stored op details and sends members to Join Ops.</small></div><label><input type="checkbox" checked={editor.discordAnnouncementEnabled!==false} onChange={e=>editorSetter({...editor,discordAnnouncementEnabled:e.target.checked})}/><span>{editor.discordAnnouncementEnabled!==false?"Enabled":"Disabled"}</span></label></div>{editor.discordAnnouncementEnabled!==false&&<>{discordStructure?<div className="op-discord-targeting">
            <button type="button" className={`op-discord-everyone ${!(editor.discordNotifyRoleIds??[]).length&&!(editor.discordNotifyUserIds??[]).length?"selected":""}`} onClick={()=>editorSetter({...editor,discordNotifyRoleIds:[],discordNotifyUserIds:[]})}><span><strong>@everyone</strong><small>Default when no specific role/member is selected</small></span><em>{!(editor.discordNotifyRoleIds??[]).length&&!(editor.discordNotifyUserIds??[]).length?"ACTIVE":"USE DEFAULT"}</em></button>
            <div className="op-discord-target-tables">
              <details className="op-discord-target-table">
                <summary><span><strong>Discord roles</strong><small>Choose one or more server roles</small></span><em>{(editor.discordNotifyRoleIds??[]).length}/{discordStructure.roles.length}</em></summary>
                <div className="op-discord-target-head"><span>Role</span><span>Status</span><span>Ping</span></div>
                <div className="op-discord-target-rows">{discordStructure.roles.map(role=>{const chosen=(editor.discordNotifyRoleIds??[]).includes(role.id);return <label key={role.id} className={chosen?"selected":""}><span><strong>@{role.name}</strong><small>Discord server role</small></span><em className={role.mentionable?"ready":"permission"}>{role.mentionable?"Mentionable":"Bot permission"}</em><input type="checkbox" checked={chosen} onChange={()=>editorSetter({...editor,discordNotifyRoleIds:chosen?(editor.discordNotifyRoleIds??[]).filter(id=>id!==role.id):[...(editor.discordNotifyRoleIds??[]),role.id]})}/></label>;})}</div>
              </details>
              <details className="op-discord-target-table">
                <summary><span><strong>Discord server members</strong><small>Ping individual people by their Discord server identity</small></span><em>{(editor.discordNotifyUserIds??[]).length}/{discordStructure.membersAvailable?discordStructure.members.length:0}</em></summary>
                {discordStructure.membersAvailable?<><input className="op-discord-member-search" value={discordMemberQuery} onChange={event=>setDiscordMemberQuery(event.target.value)} placeholder="Filter server members..."/><div className="op-discord-target-head member"><span>Member</span><span>Discord</span><span>Ping</span></div><div className="op-discord-target-rows">{discordStructure.members.filter(member=>{const needle=discordMemberQuery.trim().toLowerCase();return !needle||member.displayName.toLowerCase().includes(needle)||member.username.toLowerCase().includes(needle);}).map(member=>{const chosen=(editor.discordNotifyUserIds??[]).includes(member.id);return <label key={member.id} className={chosen?"selected":""}><span><strong>{member.displayName}</strong><small>@{member.username}</small></span><em className="ready">Direct mention</em><input type="checkbox" checked={chosen} onChange={()=>editorSetter({...editor,discordNotifyUserIds:chosen?(editor.discordNotifyUserIds??[]).filter(id=>id!==member.id):[...(editor.discordNotifyUserIds??[]),member.id]})}/></label>;})}</div>{discordStructure.membersTruncated&&<small className="op-discord-member-note">Member list is very large; SageBot returned the first 10,000 Discord members.</small>}</>:<div className="op-discord-members-unavailable"><strong>Server member list unavailable</strong><span>Roles still work. Enable Discord's <b>Server Members Intent</b> for SageBot in the Discord Developer Portal, then refresh Sage.</span></div>}
              </details>
            </div>
          </div>:<div className="op-discord-unavailable"><strong>Server roles unavailable</strong><span>The operation will still broadcast in Sage. Configure/install SageBot in Discord Setup to announce it to Discord.</span></div>}<small className="op-discord-help">No role or server member selected uses @everyone. Selecting any roles or members replaces @everyone for this operation.</small></>}</div>
        <div className="op-role-builder op-panel-inner"><div className="op-role-builder-head"><div><strong>Ships & roles</strong><small>Set demand, preferred hull and role notes.</small></div><button onClick={()=>editorSetter({...editor,roles:[...editor.roles,blankRole(`Role ${editor.roles.length+1}`,30+Math.random()*40,30+Math.random()*40)]})}>+ Add Role</button></div>{editor.roles.map(role=><article key={role.id}><input value={role.label} onChange={e=>updateRole(editor,role.id,{label:e.target.value},editorSetter)} placeholder="Role"/><input list="op-ship-catalogue" value={role.hullName} onChange={e=>setRoleHull(editor,role.id,e.target.value,editorSetter)} placeholder="Ship / hull (optional)"/><input type="number" min={1} value={role.count} onChange={e=>updateRole(editor,role.id,{count:Math.max(1,Number(e.target.value)||1)},editorSetter)}/><input value={role.notes} onChange={e=>updateRole(editor,role.id,{notes:e.target.value},editorSetter)} placeholder="Role notes"/><button onClick={()=>editorSetter({...editor,roles:editor.roles.filter(r=>r.id!==role.id)})}>Remove</button></article>)}</div>
      </div>
      <div className="op-tactical-panel op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">TACTICAL BOARD</p><h4>Formation layout</h4></div><small>Drag role cards to position them.</small></div><TacticalBoard payload={editor} editable onChange={editorSetter}/></div>
    </div>
    <div className="op-editor-actions"><small>Backend authorization is checked again when this operation is published or updated.</small><div><button onClick={()=>{setCreating(false);setDraft(null);setEditing(null);}}>Cancel</button><button className="primary" onClick={()=>void (creating?broadcast():saveEdit())} disabled={busy}>{creating?"Broadcast Operation":"Save & Rebroadcast"}</button></div></div>
  </section>}

  function CommandView(){if(editor)return Editor();return <div className="op-command-shell">
    {!canCommand&&<div className="op-permission-callout op-panel"><div><strong>Command permissions not granted</strong><span>Your verified corporation membership can join operations, but your current EVE roles are not authorised to manage or approve them.</span></div><button onClick={()=>setMode("join")}>Open Join Ops</button></div>}
    <div className="op-live-layout"><OperationList ops={ops} selectedId={selected?.summary.id??""} onSelect={setSelectedId} title="Command broadcasts"/><main className="op-live-main op-panel">{selected&&activePayload?<>
      <div className="op-live-title"><div><p className="eyebrow">{activePayload.operationType} Â· {activePayload.status.toUpperCase()}</p><h3>{activePayload.title}</h3><p>{activePayload.description||"No additional orders."}</p><small>{activePayload.formupSystem?`Form-up ${activePayload.formupSystem} Â· `:""}{activePayload.startsAt?new Date(activePayload.startsAt).toLocaleString():"Start time TBD"} Â· Approval {activePayload.approvalRequired!==false?"ON":"AUTO"} Â· Fit review {activePayload.fitCheckEnabled?"ON":"OFF"}</small>{canManage&&<div className="op-leadership-strip"><span>Owner <strong>{(activePayload.operationOwner??activePayload.createdBy).characterName}</strong></span><small>{(activePayload.notificationLeaderCharacterIds??[]).length} leader{(activePayload.notificationLeaderCharacterIds??[]).length===1?"":"s"} notified</small>{(activePayload.operationOwner??activePayload.createdBy).characterId!==characterId&&<button onClick={()=>void takeOwnership()} disabled={busy}>Take Ownership</button>}<button className={(activePayload.notificationLeaderCharacterIds??[]).includes(characterId)?"active":""} onClick={()=>void toggleMyNotifications()} disabled={busy}>{(activePayload.notificationLeaderCharacterIds??[]).includes(characterId)?"Notifications On":"Add me to notifications"}</button></div>}</div>{canManage&&activePayload.status!=="cancelled"&&activePayload.status!=="complete"&&<div className="op-live-actions"><button onClick={()=>void announceSelected()} disabled={busy}>Announce in Discord</button><button onClick={()=>setEditing(structuredClone(activePayload))}>Edit Plan / Map</button><button className="op-cancel-button" onClick={()=>{setCancelOpen(true);setCancelMessage("");}} disabled={busy}>Cancel Operation</button></div>}</div>
      {activePayload.status==="cancelled"&&<div className="op-cancelled-banner"><div><p className="eyebrow">OPERATION CANCELLED</p><strong>This operation has been stood down.</strong><span>{activePayload.cancellationMessage||"No cancellation message was provided."}</span></div><small>{activePayload.cancelledBy?.characterName?`Cancelled by ${activePayload.cancelledBy.characterName}`:"Cancelled by leadership"}{activePayload.cancelledAt?` · ${new Date(activePayload.cancelledAt).toLocaleString()}`:""}</small></div>}
      {cancelOpen&&activePayload.status!=="cancelled"&&<section className="op-cancel-confirm op-panel-inner"><div><p className="eyebrow">CANCEL OPERATION</p><h4>Stand down {activePayload.title}</h4><p>Members will no longer be able to request roles. Any pending applications will be closed.</p></div><label><span>Cancellation message · optional</span><textarea value={cancelMessage} maxLength={600} onChange={e=>setCancelMessage(e.target.value)} placeholder="Reason for cancellation / stand-down instructions..."/></label><div><button onClick={()=>{setCancelOpen(false);setCancelMessage("");}} disabled={busy}>Keep Operation</button><button className="op-confirm-cancel" onClick={()=>void cancelSelected()} disabled={busy}>Confirm Cancellation</button></div></section>}
      <div className="op-tactical-panel op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">TACTICAL OVERVIEW</p><h4>Approved formation</h4></div><small>Created by {activePayload.createdBy.characterName}</small></div><TacticalBoard payload={activePayload} editable={false}/></div>
      <section className="op-role-choices op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">ROLE DEMAND</p><h4>Ship requirements</h4></div><small>{activePayload.roles.length} role groups</small></div>{activePayload.roles.map(role=>{const apps=activePayload.applications.filter(a=>a.roleId===role.id);const approved=apps.filter(a=>a.status==="approved").length;return <article key={role.id} className={approved>=role.count?"filled":""}><div>{role.hullTypeId>0&&<img src={assetUrl(role.hullTypeId)} alt=""/>}<span><strong>{role.label}</strong><small>{role.hullName||"Any suitable hull"} Â· {approved}/{role.count} approved</small><em>{role.notes}</em></span></div></article>;})}</section>
      {activePayload.status!=="cancelled"&&(activePayload.approvalRequired!==false?(canApprove?<section className="op-approval-queue op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">APPLICATION APPROVAL</p><h4>{pending.length} pending request{pending.length===1?"":"s"}</h4></div><small>Controlled by the separate approval permission</small></div>{pending.map(app=><article key={app.id}><div><strong>{app.characterName}</strong><span>{roleFor(activePayload,app.roleId)?.label??"Unknown role"} Â· {app.hullName||"Hull not stated"}</span><small>{new Date(app.submittedAt).toLocaleString()}</small></div>{app.fitText?<button className="op-view-fit" onClick={()=>setViewFitApp(app)}>View fit Â· {app.fitName||app.hullName||"Submitted fit"}</button>:<span className="op-no-fit">No fit submitted</span>}<input value={decisionMessages[app.id]??""} onChange={e=>setDecisionMessages(current=>({...current,[app.id]:e.target.value}))} placeholder="Optional approval / denial message"/><button onClick={()=>void decide(app,"denied")}>Deny</button><button className="approve" onClick={()=>void decide(app,"approved")}>Approve</button></article>)}{!pending.length&&<div className="op-empty-state compact"><strong>Approval queue clear</strong><span>New member role requests will appear here.</span></div>}</section>:canManage&&<div className="op-permission-note">You can manage operation plans, but application decisions require the separate approval permission.</div>):<div className="op-auto-approval-note"><strong>Automatic role approval is enabled</strong><span>This operation creator disabled leadership approval. New valid requests go straight into the approved formation.</span></div>)}
    </>:<div className="op-empty-state"><strong>Select a command broadcast</strong><span>Choose an operation from the left to inspect its tactical plan and applications.</span></div>}</main></div>
  </div>}

  function JoinView(){const payload=selected?.payload;const creatorIsCurrent=payload?.createdBy.characterId===characterId;return <div className="op-join-shell"><div className="op-live-layout op-join-layout"><OperationList ops={ops} selectedId={selected?.summary.id??""} onSelect={setSelectedId} title="Operations"/><main className="op-live-main op-panel">{selected&&payload?<>
      <div className="op-live-title"><div><p className="eyebrow">JOIN OP Â· {payload.operationType}</p><h3>{payload.title}</h3><p>{payload.description||"No additional orders."}</p><small>{payload.formupSystem?`Form-up ${payload.formupSystem} Â· `:""}{payload.startsAt?new Date(payload.startsAt).toLocaleString():"Start time TBD"} Â· Approval {payload.approvalRequired!==false?"ON":"AUTO"} Â· Fit review {payload.fitCheckEnabled?"ON":"OFF"}</small>{creatorIsCurrent&&<span className="op-creator-self-note">You created this operation. You can still request any available role like every other member.</span>}</div></div>
      {payload.status==="cancelled"&&<div className="op-cancelled-banner"><div><p className="eyebrow">OPERATION CANCELLED</p><strong>This operation has been stood down.</strong><span>{payload.cancellationMessage||"No cancellation message was provided."}</span></div><small>{payload.cancelledBy?.characterName?`Cancelled by ${payload.cancelledBy.characterName}`:"Cancelled by leadership"}{payload.cancelledAt?` · ${new Date(payload.cancelledAt).toLocaleString()}`:""}</small></div>}
      <div className="op-join-overview-grid"><div className="op-tactical-panel op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">FORMATION</p><h4>Current approved ships</h4></div></div><TacticalBoard payload={payload} editable={false}/></div>
      <section className="op-role-choices op-panel-inner"><div className="op-section-title"><div><p className="eyebrow">AVAILABLE ROLES</p><h4>Choose where you want to fly</h4></div></div>{payload.roles.map(role=>{const approved=payload.applications.filter(a=>a.roleId===role.id&&a.status==="approved").length;return <article key={role.id} className={`${approved>=role.count?"filled":""}${applyRoleId===role.id?" selected":""}`}><div>{role.hullTypeId>0&&<img src={assetUrl(role.hullTypeId)} alt=""/>}<span><strong>{role.label}</strong><small>{role.hullName||"Any suitable hull"} Â· {approved}/{role.count} approved</small><em>{role.notes}</em></span></div><button disabled={!canJoin||payload.status==="cancelled"||myApp?.status==="pending"||myApp?.status==="approved"} onClick={()=>setApplyRoleId(role.id)}>{payload.status==="cancelled"?"Operation Cancelled":approved>=role.count?"Request Anyway":"Request Role"}</button></article>;})}</section></div>
      {myApp&&<div className={`op-my-application ${myApp.status}`}><div><strong>Your application Â· {myApp.status.toUpperCase()}</strong><span>{roleFor(payload,myApp.roleId)?.label??"Role"}{myApp.fitName?` Â· ${myApp.fitName}`:""}</span></div>{myApp.message&&<p>Leadership message: {myApp.message}</p>}{myApp.status==="denied"&&payload.status!=="cancelled"&&<small>You may submit a new request for another role.</small>}</div>}
      {applyRoleId&&payload.status!=="cancelled"&&<section className="op-apply-panel op-panel-inner"><div className="op-apply-heading"><p className="eyebrow">ROLE REQUEST</p><h4>Request {roleFor(payload,applyRoleId)?.label}</h4><p>{payload.approvalRequired===false?"Leadership approval is disabled. Your valid role request will be approved immediately.":payload.fitCheckEnabled?"Fit review is enabled. Submit the fit you intend to fly for leadership review.":"No fit is required. Leadership will review the role request only."}</p></div><label><span>Hull</span><input list="op-ship-catalogue" value={hullName} onChange={e=>setHullName(e.target.value)} placeholder={roleFor(payload,applyRoleId)?.hullName||"Ship / hull"}/></label>{payload.approvalRequired!==false&&payload.fitCheckEnabled&&<><label><span>Fit name</span><input value={fitName} onChange={e=>setFitName(e.target.value)}/></label><label className="op-apply-fit"><span>Fit Â· Sage JSON / EFT</span><textarea value={fitText} onChange={e=>setFitText(e.target.value)} placeholder="Paste a Sage JSON or EFT / PYFA fit"/></label></>}<div className="op-apply-actions"><button onClick={()=>setApplyRoleId("")}>Cancel</button><button className="primary" onClick={()=>void apply()} disabled={busy||(payload.approvalRequired!==false&&payload.fitCheckEnabled&&!fitText.trim())}>Submit Request</button></div></section>}
    </>:<div className="op-empty-state"><strong>No operation selected</strong><span>Choose a broadcast operation to view its roles and submit yourself for a slot.</span></div>}</main></div></div>}

  return <div className="corp-op-planner"><header className="op-planner-head"><div><p className="eyebrow">CORPORATION Â· OPERATION PLANNER</p><h3>Corporation Operations</h3><p>Command planning and member participation are separated so leaders can manage the fleet without losing access to the same Join Ops workflow as everyone else.</p></div><div className="op-head-actions"><button onClick={()=>void load()} disabled={busy}>Refresh</button>{mode==="command"&&canManage&&!editor&&<button className="primary" onClick={startCreate}>Create Operation</button>}</div></header>
    <nav className="op-mode-tabs" aria-label="Operation planner views"><button className={mode==="command"?"active":""} onClick={()=>setMode("command")}><strong>Command Ops</strong><span>Create, broadcast, edit & approve</span>{canCommand&&<em>Authorised</em>}</button><button className={mode==="join"?"active":""} onClick={()=>setMode("join")}><strong>Join Ops</strong><span>Browse operations & request roles</span><em>All verified members</em></button></nav>
    <div className="op-status">{status}</div>
    <datalist id="op-ship-catalogue">{ships.map(ship=><option key={ship.typeId} value={ship.name}>{ship.groupName}</option>)}</datalist>
    {mode==="command"?CommandView():JoinView()}
    {viewFitApp&&<OperationFitPreview fitText={viewFitApp.fitText} fitName={viewFitApp.fitName} hullName={viewFitApp.hullName} onClose={()=>setViewFitApp(null)}/>}
  </div>;
}
