import { FormEvent, useState } from "react";
import type { CharacterSnapshot, RawMarketSearchOrder, RawMarketSearchResult } from "./types";
import { friendlyAnalysisError, isExpectedAnalysisCancellation } from "./analysis-errors";
import type { ShoppingListAdd } from "./shopping-list";
export type { ShoppingListAdd } from "./shopping-list";
type HubScope = "all-hubs"|"jita"|"amarr"|"dodixie"|"hek"|"rens"|"new-eden";
const HUBS:Record<Exclude<HubScope,"all-hubs"|"new-eden">,string>={jita:"Jita",amarr:"Amarr",dodixie:"Dodixie",hek:"Hek",rens:"Rens"};
const money=(value:number)=>new Intl.NumberFormat("en-GB",{maximumFractionDigits:2}).format(value);
const nullable=(value:string)=>{const parsed=Number(value.replace(/,/g,""));return value.trim()&&Number.isFinite(parsed)?parsed:null;};

function scopeSystems(scope:HubScope){if(scope==="new-eden")return[];if(scope==="all-hubs")return Object.values(HUBS);return[HUBS[scope]];}
function OrderList({title,side,orders}:{title:string;side:"buy"|"sell";orders:RawMarketSearchOrder[]}){
  return <section className={`market-v2-order-column ${side}`}><header><div><span>{side==="sell"?"SELL ORDERS":"BUY ORDERS"}</span><h4>{title}</h4></div><strong>{orders.length}</strong></header>
    <div className="market-v2-depth-head"><span>Price</span><span>Remaining</span><span>Location</span><span>Jumps</span></div>
    {orders.map(order=><div className="market-v2-depth-row" key={order.orderId}><span><strong>{money(order.price)} ISK</strong><small>min {order.minVolume.toLocaleString()}</small></span><span><strong>{order.volumeRemain.toLocaleString()}</strong><small>of {order.volumeTotal.toLocaleString()}</small></span><span><strong>{order.systemName}</strong><small>{order.locationName}</small></span><span><strong>{order.jumpsFromOrigin==null?"-":order.jumpsFromOrigin>=999?"unreachable":order.jumpsFromOrigin}</strong><small>{order.securityBand}</small></span></div>)}
    {!orders.length&&<div className="market-v2-empty">No matching {side} orders.</div>}
  </section>;
}

export function GlobalMarketSearch({snapshot,onAddToShoppingList}:{snapshot?:CharacterSnapshot;onAddToShoppingList(item:ShoppingListAdd):void}){
  const [query,setQuery]=useState(""); const [selectedTypeId,setSelectedTypeId]=useState<number|undefined>();
  const [scope,setScope]=useState<HubScope>("all-hubs"); const [advanced,setAdvanced]=useState(false);
  const [security,setSecurity]=useState<"all"|"high"|"low"|"null">("all"); const [regionId,setRegionId]=useState("");
  const [systemQuery,setSystemQuery]=useState(""); const [locationQuery,setLocationQuery]=useState(""); const [minPrice,setMinPrice]=useState(""); const [maxPrice,setMaxPrice]=useState(""); const [minVolume,setMinVolume]=useState(""); const [maxJumps,setMaxJumps]=useState("");
  const [quantity,setQuantity]=useState("1"); const [result,setResult]=useState<RawMarketSearchResult|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [eveStatus,setEveStatus]=useState("");
  const originSystemId=Number(snapshot?.location?.solar_system_id??0)||null;
  async function search(typeId?:number){const term=query.trim();if(!term&&!typeId&&!selectedTypeId)return;setBusy(true);setError("");try{const next=await window.sage.searchRawMarket({query:term,typeId:typeId??selectedTypeId,side:"all",security:advanced?security:"all",regionId:advanced&&regionId?Number(regionId):null,minPrice:advanced?nullable(minPrice):null,maxPrice:advanced?nullable(maxPrice):null,minVolume:advanced?nullable(minVolume):null,systemNames:systemQuery.trim()?[]:scopeSystems(scope),systemQuery:advanced?systemQuery.trim():"",locationQuery:advanced?locationQuery.trim():"",originSystemId,maxJumps:advanced?nullable(maxJumps):null,sort:"sell-lowest",offset:0,limit:500});setResult(next);setSelectedTypeId(next.selectedType?.typeId);}catch(caught){if(!isExpectedAnalysisCancellation(caught))setError(friendlyAnalysisError(caught,"Market search failed."));}finally{setBusy(false);}}
  function submit(event:FormEvent){event.preventDefault();setSelectedTypeId(undefined);void search(undefined);}
  async function openInEve(){if(!snapshot?.characterId||!result?.selectedType)return setEveStatus("Select a connected character first.");setEveStatus("Opening market in EVE...");try{const opened=await window.sage.openEveMarketType({characterId:snapshot.characterId,typeId:result.selectedType.typeId});setEveStatus(`Opened for ${opened.characterName}${opened.usedFallback?" (online character)":""}.`);}catch(e){setEveStatus(e instanceof Error?e.message:"Could not open the EVE market.");}}
  const sellers=(result?.orders??[]).filter(o=>o.side==="sell").sort((a,b)=>a.price-b.price||b.volumeRemain-a.volumeRemain).slice(0,20);
  const buyers=(result?.orders??[]).filter(o=>o.side==="buy").sort((a,b)=>b.price-a.price||b.volumeRemain-a.volumeRemain).slice(0,20);
  return <section className="market-v2-search">
    <div className="market-v2-title"><div><p className="eyebrow">RETAINED PUBLIC ORDER BOOK</p><h2>Market Search</h2><p>Search one item, then compare the strongest retained buy and sell orders. Advanced filters stay out of the way until needed.</p></div>{result?.snapshot&&<small>Snapshot {new Date(result.snapshot.createdAt).toLocaleString()} · {result.snapshot.orderCount.toLocaleString()} orders</small>}</div>
    <form className="market-v2-query" onSubmit={submit}><input value={query} onChange={e=>{setQuery(e.target.value);setSelectedTypeId(undefined);}} placeholder="Search an item - e.g. Tritanium, Ishtar, Large Shield Extender II"/><select value={scope} onChange={e=>setScope(e.target.value as HubScope)}><option value="all-hubs">All major hubs</option><option value="jita">Jita</option><option value="amarr">Amarr</option><option value="dodixie">Dodixie</option><option value="hek">Hek</option><option value="rens">Rens</option>{advanced&&<option value="new-eden">All New Eden</option>}</select><button type="submit" disabled={busy||!query.trim()}>{busy?"Searching...":"Search"}</button><button type="button" className={advanced?"active":""} onClick={()=>setAdvanced(v=>!v)}>{advanced?"Hide Advanced":"Advanced"}</button></form>
    {advanced&&<div className="market-v2-advanced"><label><span>Security</span><select value={security} onChange={e=>setSecurity(e.target.value as typeof security)}><option value="all">All security</option><option value="high">High-sec</option><option value="low">Low-sec</option><option value="null">Null / 0.0</option></select></label><label><span>Region</span><select value={regionId} onChange={e=>setRegionId(e.target.value)}><option value="">Any region</option>{result?.regionOptions.map(r=><option key={r.regionId} value={r.regionId}>{r.regionName}</option>)}</select></label><label><span>System contains</span><input value={systemQuery} onChange={e=>setSystemQuery(e.target.value)} placeholder="Any system"/></label><label><span>Station / structure contains</span><input value={locationQuery} onChange={e=>setLocationQuery(e.target.value)} placeholder="Any location"/></label><label><span>Min price</span><input value={minPrice} onChange={e=>setMinPrice(e.target.value)} inputMode="decimal" placeholder="Any"/></label><label><span>Max price</span><input value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} inputMode="decimal" placeholder="Any"/></label><label><span>Min order units</span><input value={minVolume} onChange={e=>setMinVolume(e.target.value)} inputMode="numeric" placeholder="Any"/></label><label><span>Max jumps from {snapshot?.character?.name??"character"}</span><input value={maxJumps} onChange={e=>setMaxJumps(e.target.value)} inputMode="numeric" placeholder={originSystemId?"Any":"Sync character first"} disabled={!originSystemId}/></label><button type="button" onClick={()=>void search()} disabled={busy||!selectedTypeId}>Apply Advanced</button></div>}
    {error&&<div className="global-market-message error">{error}</div>}{result?.message&&<div className="global-market-message">{result.message}</div>}
    {result&&!result.selectedType&&result.typeMatches.length>0&&<div className="global-type-matches">{result.typeMatches.slice(0,30).map(item=><button key={item.typeId} onClick={()=>void search(item.typeId)}><strong>{item.name}</strong><small>{item.categoryName}</small></button>)}</div>}
    {result?.selectedType&&<><div className="market-v2-selected"><div><span>{result.selectedType.categoryName}</span><h3>{result.selectedType.name}</h3></div><div><span>Best sell</span><strong>{result.bestSell==null?"-":`${money(result.bestSell)} ISK`}</strong></div><div><span>Best buy</span><strong>{result.bestBuy==null?"-":`${money(result.bestBuy)} ISK`}</strong></div><div className="market-v2-actions"><label><span>Shopping qty</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="numeric"/></label><button type="button" onClick={()=>onAddToShoppingList({typeId:result.selectedType!.typeId,name:result.selectedType!.name,quantity:Math.max(1,Math.floor(Number(quantity)||1))})}>Add to Shopping List</button><button type="button" onClick={()=>void openInEve()}>Open in EVE</button></div></div>{eveStatus&&<div className="market-v2-status">{eveStatus}</div>}<div className="market-v2-depth"><OrderList title="Cheapest sellers" side="sell" orders={sellers}/><OrderList title="Highest buyers" side="buy" orders={buyers}/></div></>}
  </section>;
}
