import { useEffect, useMemo, useState } from "react";

type PreviewItem={name:string;typeId?:number;quantity:number;charge?:string;chargeTypeId?:number};
type PreviewFit={name:string;hull:PreviewItem;high:PreviewItem[];mid:PreviewItem[];low:PreviewItem[];rig:PreviewItem[];subsystem:PreviewItem[];drones:PreviewItem[];fighters:PreviewItem[];cargo:PreviewItem[];format:string};
type RackKey="high"|"mid"|"low"|"rig"|"subsystem";
const emptyFit=(name="Submitted fit",hull="Unknown hull",format="Fit") :PreviewFit=>({name,hull:{name:hull,quantity:1},high:[],mid:[],low:[],rig:[],subsystem:[],drones:[],fighters:[],cargo:[],format});
const imageUrl=(typeId?:number,size=64)=>typeId?`sage-asset://type/${typeId}/icon?size=${size}`:"";
const shipUrl=(typeId?:number)=>typeId?`sage-asset://type/${typeId}/render?size=512`:"";
function item(value:any):PreviewItem{if(typeof value==="string")return{name:value,quantity:1};return{name:String(value?.name??value?.typeName??(value?.typeId?`Type ${value.typeId}`:"Unknown item")),typeId:Number(value?.typeId??value?.type_id??0)||undefined,quantity:Math.max(1,Number(value?.quantity??1)||1),charge:value?.charge?String(value.charge):undefined,chargeTypeId:Number(value?.chargeTypeId??value?.charge_type_id??0)||undefined};}
function eftItem(line:string):PreviewItem{const q=line.match(/\s+x(\d+)\s*$/i);const clean=line.replace(/\s+x\d+\s*$/i,"").trim();const [name,...charge]=clean.split(",").map(v=>v.trim());return{name,quantity:q?Number(q[1]):1,charge:charge.join(", ")||undefined};}
function flagRack(flag:string):RackKey|"drones"|"fighters"|"cargo"|null{const f=flag.toLowerCase();if(f.startsWith("hislot"))return"high";if(f.startsWith("medslot"))return"mid";if(f.startsWith("loslot"))return"low";if(f.startsWith("rigslot"))return"rig";if(f.startsWith("subsystemslot"))return"subsystem";if(f.includes("drone"))return"drones";if(f.includes("fighter"))return"fighters";if(f.includes("cargo"))return"cargo";return null;}
function parseFit(text:string,fitName?:string,hullName?:string):PreviewFit{
  const trimmed=text.trim().replace(/^```(?:json|eft)?\s*/i,"").replace(/```$/i,"").trim();
  if(!trimmed)throw new Error("No fitting data was submitted.");
  if(trimmed.startsWith("{")){const raw=JSON.parse(trimmed) as any;
    if(Array.isArray(raw?.items)&&(raw?.ship_type_id||raw?.shipTypeId)){const fit=emptyFit(fitName||raw.name||"Submitted ESI fit",hullName||"Unknown hull","ESI JSON");fit.hull.typeId=Number(raw.ship_type_id??raw.shipTypeId)||undefined;for(const row of raw.items){const rack=flagRack(String(row?.flag??row?.location_flag??""));if(rack)fit[rack].push(item(row));}return fit;}
    const modules=raw.modules??raw;const hull=item(raw.ship??raw.hull??hullName??"Unknown hull");return{name:String(raw.name??fitName??`${hull.name} fitting`),hull,high:(modules.high??[]).map(item),mid:(modules.mid??[]).map(item),low:(modules.low??[]).map(item),rig:(modules.rig??[]).map(item),subsystem:(modules.subsystem??[]).map(item),drones:(raw.drones??[]).map(item),fighters:(raw.fighters??[]).map(item),cargo:(raw.cargo??[]).map(item),format:"Sage JSON"};}
  const dna=trimmed.match(/^(\d+):(.+):$/);if(dna){const fit=emptyFit(fitName||"Submitted DNA fit",hullName||`Type ${dna[1]}`,"DNA");fit.hull.typeId=Number(dna[1]);for(const token of dna[2].split(":")){const match=token.match(/^(\d+);(\d+)$/);if(match)fit.cargo.push({name:`Type ${match[1]}`,typeId:Number(match[1]),quantity:Number(match[2])});}return fit;}
  const lines=trimmed.split(/\r?\n/);const header=lines.shift()?.match(/^\[(.+?),\s*(.+?)\]$/);if(header){const groups:string[][]=[[]];for(const line of lines){if(!line.trim()){if(groups.at(-1)?.length)groups.push([]);continue;}if(!/^\[Empty .* slot\]$/i.test(line.trim()))groups.at(-1)!.push(line.trim());}const [low=[],mid=[],high=[],rig=[],subsystem=[],drones=[],cargo=[]]=groups.filter(g=>g.length);return{name:fitName||header[2],hull:{name:hullName||header[1],quantity:1},low:low.map(eftItem),mid:mid.map(eftItem),high:high.map(eftItem),rig:rig.map(eftItem),subsystem:subsystem.map(eftItem),drones:drones.map(eftItem),fighters:[],cargo:cargo.map(eftItem),format:"EFT / PYFA"};}
  const fit=emptyFit(fitName||"Submitted fit",hullName||"Unknown hull","Plain text");let rack:RackKey|"drones"|"fighters"|"cargo"="cargo";for(const rawLine of [lines[0]??"",...lines.slice(1)]){const line=rawLine.trim();if(!line)continue;const section=line.replace(/[\[\]:]/g,"").toLowerCase();if(section.includes("high")){rack="high";continue;}if(section.includes("mid")){rack="mid";continue;}if(section.includes("low")){rack="low";continue;}if(section.includes("rig")){rack="rig";continue;}if(section.includes("subsystem")){rack="subsystem";continue;}if(section.includes("drone")){rack="drones";continue;}if(section.includes("fighter")){rack="fighters";continue;}if(section.includes("cargo")){rack="cargo";continue;}fit[rack].push(eftItem(line));}return fit;
}
async function resolveFit(fit:PreviewFit):Promise<PreviewFit>{const all=[fit.hull,...fit.high,...fit.mid,...fit.low,...fit.rig,...fit.subsystem,...fit.drones,...fit.fighters,...fit.cargo];const names=[...new Set(all.filter(v=>!v.typeId&&!/^Type \d+$/i.test(v.name)).flatMap(v=>[v.name,...(v.charge?[v.charge]:[])]))];const ids=[...new Set(all.flatMap(v=>v.typeId?[v.typeId]:[]))];const [byNameRows,byIdRows]=await Promise.all([names.length?window.sage.resolveFittingTypeNamesLocal(names):Promise.resolve([]),ids.length?window.sage.resolveFittingTypeIdsLocal(ids):Promise.resolve([])]);const nameMap=new Map(byNameRows.map((v:any)=>[String(v.name).toLowerCase(),Number(v.id)]));const idMap=new Map(byIdRows.map((v:any)=>[Number(v.id),String(v.name)]));const fix=(v:PreviewItem):PreviewItem=>({...v,name:v.typeId&&idMap.has(v.typeId)?idMap.get(v.typeId)!:v.name,typeId:v.typeId??nameMap.get(v.name.toLowerCase()),chargeTypeId:v.charge?(v.chargeTypeId??nameMap.get(v.charge.toLowerCase())):v.chargeTypeId});return{...fit,hull:fix(fit.hull),high:fit.high.map(fix),mid:fit.mid.map(fix),low:fit.low.map(fix),rig:fit.rig.map(fix),subsystem:fit.subsystem.map(fix),drones:fit.drones.map(fix),fighters:fit.fighters.map(fix),cargo:fit.cargo.map(fix)};}
function Rack({title,items}:{title:string;items:PreviewItem[]}){return <section className="op-fit-rack"><header><strong>{title}</strong><small>{items.length}</small></header><div>{items.length?items.map((entry,index)=><article key={`${entry.name}-${index}`}>{entry.typeId?<img src={imageUrl(entry.typeId)} alt=""/>:<span className="op-fit-noicon">?</span>}<div><strong>{entry.name}</strong><small>{entry.quantity>1?`×${entry.quantity}`:"Fitted"}{entry.charge?` · ${entry.charge}`:""}</small></div></article>):<div className="op-fit-empty-rack">No fitted items</div>}</div></section>}
export function OperationFitPreview({fitText,fitName,hullName,onClose}:{fitText:string;fitName?:string;hullName?:string;onClose:()=>void}){const [fit,setFit]=useState<PreviewFit|null>(null);const [error,setError]=useState("");useEffect(()=>{let cancelled=false;try{const parsed=parseFit(fitText,fitName,hullName);setFit(parsed);setError("");void resolveFit(parsed).then(value=>{if(!cancelled)setFit(value);}).catch(()=>undefined);}catch(caught){setError(caught instanceof Error?caught.message:"Sage could not parse this submitted fit.");}return()=>{cancelled=true;};},[fitText,fitName,hullName]);const count=useMemo(()=>fit?[...fit.high,...fit.mid,...fit.low,...fit.rig,...fit.subsystem].reduce((sum,v)=>sum+v.quantity,0):0,[fit]);return <div className="op-fit-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="op-fit-modal" role="dialog" aria-modal="true" aria-label="Submitted operation fitting"><header className="op-fit-modal-head"><div><p className="eyebrow">APPLICATION · FIT REVIEW</p><h3>{fit?.name||fitName||"Submitted fit"}</h3><p>{fit?.hull.name||hullName||"Unknown hull"}{fit?` · ${fit.format} · ${count} fitted modules`:""}</p></div><button className="op-fit-close" onClick={onClose} aria-label="Close fit">×</button></header>{error?<div className="op-fit-parse-error"><strong>Fit preview unavailable</strong><span>{error}</span></div>:fit&&<div className="op-fit-stage"><aside className="op-fit-ship-card">{fit.hull.typeId?<img src={shipUrl(fit.hull.typeId)} alt=""/>:<div className="op-fit-ship-placeholder">SHIP</div>}<strong>{fit.hull.name}</strong><small>{fit.format}</small></aside><main className="op-fit-racks"><Rack title="High slots" items={fit.high}/><Rack title="Mid slots" items={fit.mid}/><Rack title="Low slots" items={fit.low}/><Rack title="Rigs" items={fit.rig}/>{fit.subsystem.length>0&&<Rack title="Subsystems" items={fit.subsystem}/>}</main><aside className="op-fit-bays"><Rack title="Drones" items={fit.drones}/>{fit.fighters.length>0&&<Rack title="Fighters" items={fit.fighters}/>}<Rack title="Cargo" items={fit.cargo}/></aside></div>}</section></div>}
