import { useEffect, useMemo, useRef, useState } from "react";
import type { CharacterSnapshot, PlanetaryAlertSettings, PlanetaryDesignerCandidate, PlanetaryDesignerInput, PlanetaryPlanInput, PlanetaryPlanResult, PlanetaryResourceObservation, PlanetaryRevenueAnalysis, PlanetaryRevenueSettings, PlanetarySavedPlan } from "./types";
import "./planetary-advanced.css";

const compact = new Intl.NumberFormat("en-GB", { notation:"compact", maximumFractionDigits:2 });
const number = new Intl.NumberFormat("en-GB", { maximumFractionDigits:1 });
const money=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?"UNKNOWN":`${compact.format(value)} ISK`;
const pct=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?"UNKNOWN":`${value.toFixed(0)}%`;

const ALERT_LABELS:[string,string][]=[
  ["extractor-6h","Extractor expires within 6h"],["extractor-1h","Extractor expires within 1h"],["extractor-expired","Extractor expired"],
  ["factory-starvation","Factory starvation"],["broken-route","Broken / missing route"],["storage-80","Storage above 80%"],
  ["storage-90","Storage above 90%"],["storage-95","Storage above 95%"],["storage-full","Storage full"],["colony-idle","Colony idle"],
  ["production-deficit","Production deficit"],["stockpile-low","Stockpile below configured days"],["optimizer-value","Valuable optimizer recommendation"],
];
const DEFAULT_ALERTS:PlanetaryAlertSettings={enabled:Object.fromEntries(ALERT_LABELS.map(([key])=>[key,key!=="storage-80"])),extractorWarningHours:[6,1],storageThresholds:[80,90,95],stockpileDays:2,optimizerMinIskPerDay:1_000_000,overrides:{}};

function effectiveAlertSettings(settings:PlanetaryAlertSettings,scope:string){
  if(scope==="global")return settings;
  const override=settings.overrides?.[scope]??{};
  return {...settings,...override,enabled:{...(settings.enabled??{}),...(override.enabled??{})}};
}

export function PlanetaryOptimizerPanel({analysis,onReload}:{analysis:PlanetaryRevenueAnalysis;onReload:()=>void}){
  const optimizer=analysis.optimizer;
  const [settings,setSettings]=useState<PlanetaryAlertSettings>(()=>({...DEFAULT_ALERTS,...(analysis.alertSettings??{}),enabled:{...DEFAULT_ALERTS.enabled,...(analysis.alertSettings?.enabled??{})},overrides:analysis.alertSettings?.overrides??{}}));
  const [scope,setScope]=useState("global");
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState("");
  useEffect(()=>setSettings({...DEFAULT_ALERTS,...(analysis.alertSettings??{}),enabled:{...DEFAULT_ALERTS.enabled,...(analysis.alertSettings?.enabled??{})},overrides:analysis.alertSettings?.overrides??{}}),[analysis.alertSettings]);
  const current=effectiveAlertSettings(settings,scope);
  const updateScope=(patch:Partial<PlanetaryAlertSettings>)=>setSettings(previous=>{
    if(scope==="global")return {...previous,...patch};
    const overrides={...(previous.overrides??{})};
    overrides[scope]={...(overrides[scope]??{}),...patch};
    return {...previous,overrides};
  });
  const toggle=(key:string)=>updateScope({enabled:{...(scope==="global"?settings.enabled:settings.overrides?.[scope]?.enabled??{}),[key]:!(current.enabled?.[key]??true)}});
  const save=async()=>{setSaving(true);setError("");try{await window.sage.savePlanetaryAlertSettings(settings);onReload();}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setSaving(false);}};
  return <section className="pi-panel pi-optimizer-panel">
    <div className="pi-panel-head"><div><span>FIX MY PI</span><h4>Minimum-intervention empire optimizer</h4><p>Sage tries restart/reseat/routing/feed fixes first, then layout changes, spare slots and only material repurposes.</p></div><b>{optimizer?.recommendations.length??0} recommendations</b></div>
    {!optimizer?.recommendations.length?<div className="pi-empty"><strong>No useful intervention detected.</strong><span>Your synced PI estate has no optimizer action worth surfacing right now.</span></div>:<div className="pi-optimizer-grid">{optimizer.recommendations.slice(0,12).map((row,index)=><article key={row.id} className={row.destructive?"destructive":""}>
      <div><em>#{index+1} · priority {row.rank}</em><strong>{row.title}</strong><span>{row.characterName} · {row.planetLabel}</span></div>
      <p>{row.reason}</p><ul>{row.actions.map(action=><li key={action}>{action}</li>)}</ul>
      <footer><b>{row.estimatedGainIskPerDay==null?"Gain depends on next program":`${money(row.estimatedGainIskPerDay)}/day`}</b><span>Cost {row.estimatedCostIsk==null?"UNKNOWN":money(row.estimatedCostIsk)}</span><span>Confidence {pct(row.confidence*100)}</span>{row.destructive&&<em>REPURPOSE — material gain only</em>}</footer>
    </article>)}</div>}
    <div className="pi-advanced-divider"/>
    <div className="pi-panel-head"><div><span>ALERT POLICY</span><h4>Local now, backend-ready later</h4><p>Thresholds are persisted locally; per-character and per-colony overrides use the same policy model future remote channels can consume.</p></div><button onClick={()=>void save()} disabled={saving}>{saving?"Saving…":"Save alert policy"}</button></div>
    <div className="pi-alert-policy-head"><label><span>Override scope</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="global">Global</option>{analysis.empire.characters.map(character=><option key={character.characterId} value={`character:${character.characterId}`}>{character.characterName}</option>)}{analysis.empire.colonies.map(colony=><option key={`${colony.characterId}:${colony.planetId}`} value={`colony:${colony.planetId}`}>{colony.characterName} · {colony.solarSystemName} · {colony.planetType}</option>)}</select></label>
      <label><span>Low stock</span><div><input type="number" min={0.25} step={0.25} value={current.stockpileDays??2} onChange={e=>updateScope({stockpileDays:Math.max(.25,Number(e.target.value)||.25)})}/><b>days</b></div></label>
      <label><span>Optimizer alert</span><div><input type="number" min={0} step={100000} value={current.optimizerMinIskPerDay??1_000_000} onChange={e=>updateScope({optimizerMinIskPerDay:Math.max(0,Number(e.target.value)||0)})}/><b>ISK/day</b></div></label>
    </div>
    <div className="pi-alert-toggle-grid">{ALERT_LABELS.map(([key,label])=><label key={key} className={current.enabled?.[key]===false?"off":"on"}><input type="checkbox" checked={current.enabled?.[key]!==false} onChange={()=>toggle(key)}/><span>{label}</span></label>)}</div>
    {error&&<div className="pi-error inline">{error}</div>}
  </section>;
}

type FinderPlanet=PlanetaryPlanResult["systemFinder"]["planets"][number];
function latestObservation(observations:PlanetaryResourceObservation[],planetId:number,resourceTypeId:number){return observations.filter(row=>row.planetId===planetId&&Number(row.resourceTypeId)===resourceTypeId).sort((a,b)=>Date.parse(b.observedAt??"")-Date.parse(a.observedAt??""))[0]??null;}

export function PlanetarySurveyPanel({plan,snapshot,observations,setObservations}:{plan:PlanetaryPlanResult;snapshot:CharacterSnapshot;observations:PlanetaryResourceObservation[];setObservations:(next:PlanetaryResourceObservation[]|((current:PlanetaryResourceObservation[])=>PlanetaryResourceObservation[]))=>void}){
  const initial=plan.systemFinder.planets.find(row=>row.planetId===plan.layout.planetId)??plan.systemFinder.planets[0]??null;
  const [planetId,setPlanetId]=useState<number|null>(initial?.planetId??null);
  const [draft,setDraft]=useState<Record<number,string>>({});
  const [confidence,setConfidence]=useState(0.85);
  const [corp,setCorp]=useState<any>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const selected=plan.systemFinder.planets.find(row=>row.planetId===planetId)??initial;
  useEffect(()=>{if(!plan.systemFinder.planets.some(row=>row.planetId===planetId))setPlanetId(initial?.planetId??null);},[plan,planetId,initial?.planetId]);
  const record=(planet:FinderPlanet,resource:{typeId:number;name:string})=>{const value=Number(draft[resource.typeId]);if(!Number.isFinite(value)||value<0||value>100)return;const now=new Date().toISOString();const next:PlanetaryResourceObservation={planetId:planet.planetId,systemId:planet.systemId,systemName:planet.systemName,planetTypeId:planet.planetTypeId,planetType:planet.planetType,radiusKm:planet.radiusKm,resourceTypeId:resource.typeId,resourceName:resource.name,percent:value,characterId:String(snapshot.characterId),characterName:snapshot.character?.name,source:"manual-survey",confidence,scope:"personal",observedAt:now};setObservations(current=>[...current.filter(row=>!(row.scope!=="corporation"&&row.planetId===planet.planetId&&Number(row.resourceTypeId)===resource.typeId)),next]);};
  const loadCorp=async()=>{setBusy(true);setError("");try{const state=await window.sage.getPlanetaryCorpState({characterId:String(snapshot.characterId)});setCorp(state);const rows:PlanetaryResourceObservation[]=state.surveys.flatMap((entry:any)=>Array.isArray(entry.payload?.observations)?entry.payload.observations:[]).map((row:any)=>({...row,scope:"corporation",source:"sage-online"}));const key=(row:PlanetaryResourceObservation)=>`${row.planetId}:${row.resourceTypeId??row.resourceName}:${row.observedAt??""}`;setObservations(current=>{const seen=new Set(current.map(key));return [...current,...rows.filter(row=>!seen.has(key(row)))];});}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);setError("");try{await window.sage.publishPlanetaryCorpSurvey({characterId:String(snapshot.characterId),observations:observations.filter(row=>row.scope!=="corporation")});await loadCorp();}catch(value){setError(value instanceof Error?value.message:String(value));setBusy(false);}};
  return <section className="pi-panel pi-survey-panel">
    <div className="pi-panel-head"><div><span>PER-RESOURCE PLANET SURVEY</span><h4>Actual observed richness, never invented</h4><p>Every percentage is tied to a planet and resource. Multi-resource rankings use the weakest observed resource as the bottleneck; incomplete evidence stays UNKNOWN.</p></div><b>{observations.length} evidence rows</b></div>
    <div className="pi-survey-layout"><div className="pi-survey-planets">{plan.systemFinder.planets.slice(0,30).map(row=><button key={row.planetId} className={row.planetId===selected?.planetId?"active":""} onClick={()=>setPlanetId(row.planetId)}><strong>{row.systemName} {row.planetIndex?`P${row.planetIndex}`:""}</strong><span>{row.planetType} · {row.jumps}j · {number.format(row.radiusKm)} km</span><small>Bottleneck {pct(row.densityBottleneckPercent)} · evidence {pct(row.densityKnownPercent)}</small></button>)}</div>
      <div>{!selected?<div className="pi-empty">No compatible planet in finder range.</div>:<><div className="pi-survey-selected"><strong>{selected.systemName} · {selected.planetType}</strong><span>Required-compatible resources on this planet</span></div>{selected.resources.map(resource=>{const existing=latestObservation(observations,selected.planetId,resource.typeId);return <div className="pi-survey-resource" key={resource.typeId}><div><strong>{resource.name}</strong><span>{existing?.percent==null?"UNKNOWN":`${Number(existing.percent).toFixed(0)}%`} {existing?.scope==="corporation"?"· CORP":""}</span></div><input type="number" min={0} max={100} step={0.1} value={draft[resource.typeId]??existing?.percent??""} placeholder="UNKNOWN" onChange={e=>setDraft(current=>({...current,[resource.typeId]:e.target.value}))}/><button onClick={()=>record(selected,resource)}>Record %</button></div>})}<label className="pi-confidence"><span>Observation confidence</span><input type="range" min={0.25} max={1} step={0.05} value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/><b>{pct(confidence*100)}</b></label></>}</div></div>
    <div className="pi-inline-actions"><button onClick={()=>void loadCorp()} disabled={busy}>{busy?"Syncing…":"Pull corporation survey DB"}</button><button onClick={()=>void publish()} disabled={busy||!observations.some(row=>row.scope!=="corporation")}>Publish personal observations to corp</button>{corp&&<b>{corp.workspace?.corporation_name} · {corp.surveys?.length??0} survey packets</b>}</div>
    {error&&<div className="pi-error inline">{error}</div>}
  </section>;
}

type BasketRow={id:string;typeId:number;quantity:number;period:"day"|"week"};
export function PlanetaryBasketPlanner({analysis,snapshot,settings,observations}:{analysis:PlanetaryRevenueAnalysis;snapshot:CharacterSnapshot;settings:PlanetaryRevenueSettings;observations:PlanetaryResourceObservation[]}){
  const products=useMemo(()=>analysis.opportunities.filter(row=>row.tier!=="P0").sort((a,b)=>a.output.name.localeCompare(b.output.name)),[analysis.opportunities]);
  const [rows,setRows]=useState<BasketRow[]>(()=>[{id:crypto.randomUUID(),typeId:products[0]?.output.typeId??0,quantity:1000,period:"week"}]);
  const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const update=(id:string,patch:Partial<BasketRow>)=>setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row));
  const loadIndustry=()=>{const next=analysis.industryDemand.flatMap(demand=>products.some(product=>product.output.typeId===demand.typeId)?[{id:crypto.randomUUID(),typeId:demand.typeId,quantity:Math.max(1,Math.ceil(demand.baseQuantity)),period:"week" as const}]:[]);if(next.length)setRows(next);};
  const run=async()=>{setBusy(true);setError("");try{setResult(await window.sage.getPlanetaryBasket({...settings,characterId:String(snapshot.characterId),targets:rows.map(({typeId,quantity,period})=>({typeId,quantity,period})),mode:"full",originSystemId:snapshot.location.solar_system_id,maxJumps:settings.maxJumps,resourceObservations:observations}));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy(false);}};
  return <section className="pi-panel pi-basket-panel"><div className="pi-panel-head"><div><span>PRODUCTION BASKET</span><h4>Solve multiple outputs as one PI requirement</h4><p>Stockpile and current colony output are applied first; shared intermediates, external inputs, planet roles and system candidates are merged into one empire plan.</p></div><button onClick={()=>void run()} disabled={busy||rows.every(row=>!row.typeId||row.quantity<=0)}>{busy?"Optimizing…":"Optimize empire"}</button></div>
    <div className="pi-basket-rows">{rows.map(row=><div key={row.id}><select value={row.typeId} onChange={e=>update(row.id,{typeId:Number(e.target.value)})}>{products.map(product=><option key={product.output.typeId} value={product.output.typeId}>{product.tier} · {product.output.name}</option>)}</select><input type="number" min={0} value={row.quantity} onChange={e=>update(row.id,{quantity:Math.max(0,Number(e.target.value)||0)})}/><select value={row.period} onChange={e=>update(row.id,{period:e.target.value as "day"|"week"})}><option value="day">day</option><option value="week">week</option></select><button onClick={()=>setRows(current=>current.filter(item=>item.id!==row.id))}>Remove</button></div>)}</div>
    <div className="pi-inline-actions"><button onClick={()=>setRows(current=>[...current,{id:crypto.randomUUID(),typeId:products[0]?.output.typeId??0,quantity:1000,period:"week"}])}>+ Add product</button><button onClick={loadIndustry} disabled={!analysis.industryDemand.length}>Load active industry demand</button></div>
    {result&&<><div className="pi-kpis pi-kpis-6 pi-basket-kpis"><article><span>Market buy/week</span><strong>{money(result.economics.marketBuyCostPerWeek)}</strong></article><article><span>PI cost/week</span><strong>{money(result.economics.productionCostPerWeek)}</strong></article><article><span>Saving/week</span><strong className={(result.economics.savingsPerWeek??0)>=0?"positive":"negative"}>{money(result.economics.savingsPerWeek)}</strong></article><article><span>Planets required</span><strong>{result.allocation.planetsRequired}</strong><small>{result.allocation.deficit?`${result.allocation.deficit} slots short`:`${result.allocation.sparePlanets} spare`}</small></article><article><span>Hauling</span><strong>{result.economics.tripsPerWeek} trips/wk</strong><small>{number.format(result.economics.totalM3PerDay)} m³/day</small></article><article><span>Layout checks</span><strong>{result.feasibility.allLayoutsFit?"FIT":"CHECK"}</strong><small>{result.feasibility.plansChecked} target plans</small></article></div>
      <div className="pi-three-col"><div><h6>Merged processor chain</h6>{result.processors.slice(0,30).map((row:any)=><div className="pi-advanced-row" key={row.schematicId}><strong>{row.outputName}</strong><span>{number.format(row.equivalent)} eq · {row.dedicated} dedicated</span></div>)}</div><div><h6>Shortages after stockpile</h6>{result.shortages.length?result.shortages.slice(0,30).map((row:any)=><div className="pi-advanced-row" key={row.typeId}><strong>{row.name}</strong><span>{number.format(row.shortage)} short / {result.horizonDays}d</span></div>):<p>Covered by stockpile/current production.</p>}</div><div><h6>Best combined systems</h6>{result.systemCandidates.slice(0,15).map((row:any)=><div className="pi-advanced-row" key={row.systemId}><strong>{row.systemName}</strong><span>{row.jumps}j · covers {row.targetCoverage} target plans · bottleneck {pct(row.densityBottleneckPercent)}</span></div>)}</div></div></>}
    {error&&<div className="pi-error inline">{error}</div>}
  </section>;
}

type DesignerNode=PlanetaryDesignerInput["nodes"][number];
type DesignerState=PlanetaryDesignerInput;

function designerFromPlan(plan:PlanetaryPlanResult):DesignerState{
  const palette=plan.layout.designerPalette??[];const nodes:DesignerNode[]=[];const links:Array<{sourceId:string;destinationId:string;level?:number}>=[];
  if(plan.layout.commandCenter)nodes.push({id:"cc",typeId:plan.layout.commandCenter.typeId,x:-.18,y:0,label:"Command Center"});
  const launchpadType=plan.layout.launchpad?.typeId;let templatePinIndex=1;for(let i=0;i<(plan.layout.launchpads||1);i++)if(launchpadType)nodes.push({id:`lp-${i}`,typeId:launchpadType,x:i*.12,y:0,label:`Launchpad ${i+1}`,templatePinIndex:i===0?templatePinIndex++:undefined});
  let p=0;for(const row of plan.chain.processors){const inputM3PerHour=row.inputs.reduce((sum,input)=>sum+input.volumePerDayM3,0)/24;const outputM3PerHour=row.output.volumePerDayM3/24;for(let count=0;count<row.dedicated;count++){const angle=(p+1)*2.399963;const radius=.36+.08*Math.floor(p/10);const facility=plan.layout.facilities.find((facility:any)=>facility.schematicId===row.schematicId)?.facility;const id=`p-${row.schematicId}-${count}`;nodes.push({id,typeId:Number(facility?.typeId??0),x:Math.cos(angle)*radius,y:Math.sin(angle)*radius,label:row.outputName,schematicId:row.schematicId,productTypeId:row.outputTypeId,templatePinIndex:templatePinIndex++,inputM3PerHour,outputM3PerHour,inputUnitsPerHour:row.inputs.reduce((sum,input)=>sum+input.quantityPerDay,0)/24,outputUnitsPerHour:row.output.quantityPerDay/24});if(launchpadType)links.push({sourceId:"lp-0",destinationId:id,level:0});p++;}}
  return {planetTypeId:plan.layout.planetTypeId,targetTypeId:plan.target.typeId,planetType:plan.layout.planetType,planetRadiusKm:plan.layout.planetRadiusKm,ccuLevel:plan.layout.ccuLevel,commandCenter:plan.layout.commandCenter,palette,nodes:nodes.filter(node=>node.typeId>0),links};
}

export function PlanetaryDesigner({plan,snapshot,currentInput,initialLayout,onTemplateSaved}:{plan:PlanetaryPlanResult;snapshot:CharacterSnapshot;currentInput:PlanetaryPlanInput;initialLayout?:PlanetaryDesignerInput|null;onTemplateSaved?:(plan:PlanetarySavedPlan)=>void}){
  const starting=()=>initialLayout&&initialLayout.planetTypeId===plan.layout.planetTypeId&&(!initialLayout.targetTypeId||initialLayout.targetTypeId===plan.target.typeId)?initialLayout:designerFromPlan(plan);
  const [open,setOpen]=useState(false);const [designer,setDesigner]=useState<DesignerState>(starting);const [result,setResult]=useState<any>(null);const [dragging,setDragging]=useState<string|null>(null);const [selected,setSelected]=useState<string|null>(null);const [linkFrom,setLinkFrom]=useState<string|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [candidates,setCandidates]=useState<PlanetaryDesignerCandidate[]>([]);const [suggesting,setSuggesting]=useState(false);const [activeProfile,setActiveProfile]=useState<string>(initialLayout?"saved":"custom");const planetRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{setDesigner(starting());setResult(null);setCandidates([]);setActiveProfile(initialLayout?"saved":"custom");},[plan.generatedAt,plan.layout.planetTypeId,plan.target.typeId,initialLayout]);
  useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void window.sage.evaluatePlanetaryLayout(designer).then(setResult).catch(value=>setError(value instanceof Error?value.message:String(value))),100);return()=>clearTimeout(timer);},[designer,open]);
  const move=(event:React.PointerEvent<HTMLDivElement>)=>{if(!dragging||!planetRef.current)return;const r=planetRef.current.getBoundingClientRect();const x=Math.max(-.95,Math.min(.95,((event.clientX-r.left)/r.width-.5)*2));const y=Math.max(-.95,Math.min(.95,((event.clientY-r.top)/r.height-.5)*2));setDesigner(current=>({...current,nodes:current.nodes.map(node=>node.id===dragging?{...node,x,y}:node)}));setActiveProfile("custom");};
  const add=(typeId:number)=>{const item=designer.palette.find(row=>row.typeId===typeId);if(!item)return;const id=`n-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;setDesigner(current=>({...current,nodes:[...current.nodes,{id,typeId,x:.05,y:.05,label:item.name}]}));setActiveProfile("custom");};
  const nodeClick=(id:string)=>{if(linkFrom&&linkFrom!==id){setDesigner(current=>current.links.some(link=>(link.sourceId===linkFrom&&link.destinationId===id)||(link.sourceId===id&&link.destinationId===linkFrom))?current:{...current,links:[...current.links,{sourceId:linkFrom,destinationId:id,level:0}]});setLinkFrom(null);setActiveProfile("custom");}setSelected(id);};
  const removeSelected=()=>{if(!selected)return;setDesigner(current=>({...current,nodes:current.nodes.filter(node=>node.id!==selected),links:current.links.filter(link=>link.sourceId!==selected&&link.destinationId!==selected)}));setSelected(null);setLinkFrom(null);setActiveProfile("custom");};
  const loadCurrent=async()=>{if(plan.layout.planetId==null){setError("Choose a synced current colony planet in the finder first.");return;}setError("");try{const seeded=await window.sage.getPlanetaryDesignerSeed({characterId:String(snapshot.characterId),planetId:plan.layout.planetId,designer});setDesigner(current=>({...current,nodes:seeded.nodes.map((node:any)=>({...node,label:node.label??current.palette.find(item=>item.typeId===node.typeId)?.name})),links:seeded.links.map((link:any)=>({sourceId:String(link.sourceId),destinationId:String(link.destinationId),level:link.level}))}));setResult(seeded);setCandidates([]);setActiveProfile("esi-current");}catch(value){setError(value instanceof Error?value.message:String(value));}};
  const suggest=async()=>{setSuggesting(true);setError("");try{setCandidates(await window.sage.generatePlanetaryLayouts(designer));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setSuggesting(false);}};
  const applyCandidate=(candidate:PlanetaryDesignerCandidate)=>{setDesigner(candidate.layout);setResult(candidate.result);setActiveProfile(candidate.profile);setSelected(null);setLinkFrom(null);setNotice(`Applied ${candidate.label}. You can still drag or edit every pin.`);};
  const buildEve=()=>window.sage.buildPlanetaryDesignerEveTemplate({designer,baseTemplate:plan.eveTemplate,comment:`Sage - ${plan.target.name} - ${activeProfile}`});
  const copyEve=async()=>{setError("");setNotice("");try{const built=await buildEve();if(!built.template)throw new Error(built.warnings.join(" ")||"No EVE template could be generated.");await window.sage.copyText(JSON.stringify(built.template));setNotice(built.warnings.length?`EVE template copied with ${built.warnings.length} warning(s): ${built.warnings.join(" ")}`:"EVE template copied from the current 2D layout.");}catch(value){setError(value instanceof Error?value.message:String(value));}};
  const saveLayout=async()=>{const name=window.prompt("Custom PI layout name",`${plan.target.name} - ${activeProfile}`)?.trim();if(!name)return;setError("");try{const built=await buildEve();const saved=await window.sage.savePlanetaryPlan({id:`tpl-${Date.now()}`,name,savedAt:new Date().toISOString(),input:currentInput,kind:"template",category:"Custom Layout",scope:"personal",designerLayout:designer,eveTemplate:built.template,layoutProfile:activeProfile});onTemplateSaved?.(saved);setNotice(`Saved ${name} as a reusable layout template.`);if(built.warnings.length)setNotice(previous=>`${previous} Export warning: ${built.warnings.join(" ")}`);}catch(value){setError(value instanceof Error?value.message:String(value));}};
  return <section className="pi-panel pi-designer-panel"><div className="pi-panel-head"><div><span>COLONY DESIGNER</span><h4>Interactive 2D layout with optimal builds</h4><p>Facility CPU/PG comes from CCP SDE. Link CPU/PG is explicitly estimated from your proposed geometry and planet radius.</p></div><button onClick={()=>setOpen(!open)}>{open?"Close designer":"Edit layout"}</button></div>{open&&<><div className="pi-designer-toolbar"><button onClick={()=>void suggest()} disabled={suggesting}>{suggesting?"Optimising…":"Suggest optimal builds"}</button><button onClick={()=>void loadCurrent()} disabled={plan.layout.planetId==null}>Use current ESI colony</button><button onClick={()=>selected&&setLinkFrom(selected)} disabled={!selected}>{linkFrom?"Choose destination…":"Link selected"}</button><button onClick={removeSelected} disabled={!selected}>Delete selected</button><button onClick={()=>{setDesigner(designerFromPlan(plan));setSelected(null);setLinkFrom(null);setCandidates([]);setActiveProfile("plan");}}>Reset to plan</button><button onClick={()=>void saveLayout()}>Save layout template</button><button onClick={()=>void copyEve()} disabled={!result?.fits}>Copy current EVE template</button></div>
    {!!candidates.length&&<div className="pi-optimal-layouts">{candidates.map(candidate=><article key={candidate.profile} className={activeProfile===candidate.profile?"active":""}><div><span>{candidate.label}</span><strong className={candidate.result.fits?"positive":"negative"}>{candidate.result.fits?"FITS":"DOES NOT FIT"}</strong></div><p>{candidate.description}</p><small>Throughput {pct(candidate.result.throughputPercent)} · link CPU {number.format(candidate.result.linkCpu)} · link PG {number.format(candidate.result.linkPower)} · buffer {candidate.result.bufferHours==null?"UNKNOWN":`${number.format(candidate.result.bufferHours)}h`}</small><button onClick={()=>applyCandidate(candidate)}>Use this build</button></article>)}</div>}
    <div className="pi-designer-shell"><div><div className="pi-designer-palette">{designer.palette.filter(item=>["launchpad","storage","ecu","basic","advanced","hightech","command"].includes(item.kind)).map(item=><button key={item.typeId} onClick={()=>add(item.typeId)}><strong>{item.kind}</strong><span>{item.name}</span><small>{number.format(item.cpu)} CPU · {number.format(item.power)} PG</small></button>)}</div></div>
      <div ref={planetRef} className="pi-planet-canvas" onPointerMove={move} onPointerUp={()=>setDragging(null)} onPointerLeave={()=>setDragging(null)}><svg viewBox="-1 -1 2 2" preserveAspectRatio="none">{designer.links.map((link,index)=>{const a=designer.nodes.find(node=>node.id===link.sourceId),b=designer.nodes.find(node=>node.id===link.destinationId);return a&&b?<line key={`${link.sourceId}:${link.destinationId}:${index}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null;})}</svg>{designer.nodes.map(node=><button key={node.id} className={`${selected===node.id?"selected":""} ${linkFrom===node.id?"link-source":""}`} style={{left:`${(node.x+1)*50}%`,top:`${(node.y+1)*50}%`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDragging(node.id);nodeClick(node.id);}} title={node.label??String(node.typeId)}><span>{designer.palette.find(item=>item.typeId===node.typeId)?.kind?.slice(0,3).toUpperCase()??"PIN"}</span><small>{node.label??designer.palette.find(item=>item.typeId===node.typeId)?.name}</small></button>)}</div>
      <aside className="pi-designer-stats"><h6>LIVE LAYOUT</h6><div><span>Profile</span><b>{activeProfile}</b></div><div><span>CPU</span><b>{number.format(result?.cpuUsed??0)} / {number.format(result?.cpuCapacity??0)}</b></div><div><span>Powergrid</span><b>{number.format(result?.powerUsed??0)} / {number.format(result?.powerCapacity??0)}</b></div><div><span>Facilities CPU</span><b>{number.format(result?.facilityCpu??0)}</b></div><div><span>Estimated links CPU</span><b>{number.format(result?.linkCpu??0)}</b></div><div><span>Facilities PG</span><b>{number.format(result?.facilityPower??0)}</b></div><div><span>Estimated links PG</span><b>{number.format(result?.linkPower??0)}</b></div><div><span>Throughput</span><b>{pct(result?.throughputPercent)}</b></div><div><span>Storage</span><b>{number.format(result?.storageCapacityM3??0)} m³</b></div><div><span>Buffer</span><b>{result?.bufferHours==null?"UNKNOWN":`${number.format(result.bufferHours)}h`}</b></div><div><span>First bottleneck</span><b>{result?.firstBottleneck??"—"}</b></div><div><span>Fit</span><b className={result?.fits?"positive":"negative"}>{result?.fits?"FITS":"DOES NOT FIT"}</b></div><small>{result?.linkEstimateBasis}</small></aside></div>{notice&&<div className="pi-designer-notice">{notice}</div>}{error&&<div className="pi-error inline">{error}</div>}</>}
  </section>;
}

const TEMPLATE_CATEGORIES=["Extraction","P0 -> P1","24h High Yield","3-day Low Maintenance","P2 Factory","P3 Factory","Robotics","Fuel Block PI","Custom Layout","Corporation"];
export function PlanetaryTemplateLibrary({snapshot,currentInput,savedPlans,setSavedPlans,onLoad}:{snapshot:CharacterSnapshot;currentInput:PlanetaryPlanInput;savedPlans:PlanetarySavedPlan[];setSavedPlans:(next:PlanetarySavedPlan[]|((current:PlanetarySavedPlan[])=>PlanetarySavedPlan[]))=>void;onLoad:(plan:PlanetarySavedPlan)=>void}){
  const [category,setCategory]=useState("Extraction");const [busy,setBusy]=useState("");const [error,setError]=useState("");const templates=savedPlans.filter(plan=>plan.kind==="template");
  const saveTemplate=async()=>{const name=window.prompt("Template name",`PI ${category}`)?.trim();if(!name)return;setBusy("save");try{const saved=await window.sage.savePlanetaryPlan({id:`tpl-${Date.now()}`,name,savedAt:new Date().toISOString(),input:currentInput,kind:"template",category,scope:"personal"});setSavedPlans(current=>[saved,...current]);}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy("");}};
  const publish=async(plan:PlanetarySavedPlan)=>{setBusy(plan.id);setError("");try{const saved=await window.sage.publishPlanetaryCorpTemplate({characterId:String(snapshot.characterId),planId:plan.id});setSavedPlans(current=>current.map(row=>row.id===plan.id?saved:row));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy("");}};
  const unpublish=async(plan:PlanetarySavedPlan)=>{if(!plan.publishedObjectId)return;setBusy(plan.id);try{const saved=await window.sage.unpublishPlanetaryCorpObject({characterId:String(snapshot.characterId),planId:plan.id,objectId:plan.publishedObjectId});if(typeof saved!=="boolean")setSavedPlans(current=>current.map(row=>row.id===plan.id?saved:row));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy("");}};
  const pullCorp=async()=>{setBusy("pull");setError("");try{const state=await window.sage.getPlanetaryCorpState({characterId:String(snapshot.characterId)});const incoming:PlanetarySavedPlan[]=state.templates.flatMap((entry:any)=>entry.payload?.input?[{id:`corp-${entry.summary.id}`,name:String(entry.payload.name??"Corp PI template"),savedAt:String(entry.payload.savedAt??entry.summary.updated_at),input:entry.payload.input,kind:"template" as const,category:String(entry.payload.category??"Corporation"),scope:"corporation" as const,publishedObjectId:entry.summary.id,publishedVersion:entry.summary.current_version,publishedAt:entry.summary.published_at,designerLayout:entry.payload.designerLayout,eveTemplate:entry.payload.eveTemplate,layoutProfile:entry.payload.layoutProfile}]:[]);setSavedPlans(current=>{const ids=new Set(current.map(row=>row.id));return [...incoming.filter(row=>!ids.has(row.id)),...current];});}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy("");}};
  const clone=async(plan:PlanetarySavedPlan)=>{const saved=await window.sage.savePlanetaryPlan({...plan,id:`tpl-${Date.now()}`,name:`${plan.name} copy`,savedAt:new Date().toISOString(),scope:"personal",publishedObjectId:undefined,publishedVersion:undefined,publishedAt:undefined});setSavedPlans(current=>[saved,...current]);};
  const rename=async(plan:PlanetarySavedPlan)=>{const name=window.prompt("Rename PI template",plan.name)?.trim();if(!name)return;const saved=await window.sage.savePlanetaryPlan({...plan,name});setSavedPlans(current=>current.map(row=>row.id===plan.id?saved:row));};
  const remove=async(plan:PlanetarySavedPlan)=>{await window.sage.deletePlanetaryPlan(plan.id);setSavedPlans(current=>current.filter(row=>row.id!==plan.id));};
  return <section className="pi-panel pi-template-library"><div className="pi-panel-head"><div><span>COLONY TEMPLATE LIBRARY</span><h4>Reusable local + corporation layouts</h4><p>Templates build on the existing saved-plan SQLite store; publishing adds a Sage Online corporation copy without sacrificing offline use.</p></div><button onClick={()=>void pullCorp()} disabled={Boolean(busy)}>{busy==="pull"?"Pulling…":"Pull corp templates"}</button></div>
    <div className="pi-template-create"><select value={category} onChange={e=>setCategory(e.target.value)}>{TEMPLATE_CATEGORIES.map(value=><option key={value}>{value}</option>)}</select><button onClick={()=>void saveTemplate()} disabled={Boolean(busy)}>Save current as template</button></div>
    {!templates.length?<div className="pi-empty"><span>No PI templates saved yet.</span></div>:<div className="pi-template-grid">{templates.map(plan=><article key={plan.id}><span>{plan.category??"Uncategorised"}</span><strong>{plan.name}</strong><small>{plan.scope==="corporation"?"CORPORATION":"PERSONAL"}{plan.publishedAt?` · published ${new Date(plan.publishedAt).toLocaleString()}`:""}</small><div><button onClick={()=>onLoad(plan)}>Load</button><button onClick={()=>void clone(plan)}>Clone</button><button onClick={()=>void rename(plan)}>Rename</button><button onClick={()=>void window.sage.copyText(JSON.stringify(plan,null,2))}>Copy Sage</button>{plan.eveTemplate&&<button onClick={()=>void window.sage.copyText(JSON.stringify(plan.eveTemplate))}>Copy EVE</button>}{plan.publishedObjectId?<button onClick={()=>void unpublish(plan)} disabled={busy===plan.id}>Unpublish</button>:<button onClick={()=>void publish(plan)} disabled={busy===plan.id}>Publish to corp</button>}<button onClick={()=>void remove(plan)}>Delete</button></div></article>)}</div>}
    {error&&<div className="pi-error inline">{error}</div>}
  </section>;
}
