import { useCallback, useEffect, useMemo, useState } from "react";
import type { CharacterSnapshot, PlanetaryAlert, PlanetaryColonyAudit, PlanetaryFactoryOpportunity, PlanetaryPlanInput, PlanetaryPlanMode, PlanetaryPlanResult, PlanetaryResourceObservation, PlanetaryRevenueAnalysis, PlanetaryRevenueSettings, PlanetarySavedPlan, PlanetarySecurityBand, PlanetaryTier } from "./types";
import "./planetary-revenue.css";
import { PlanetaryBasketPlanner, PlanetaryDesigner, PlanetaryOptimizerPanel, PlanetarySurveyPanel, PlanetaryTemplateLibrary } from "./PlanetaryAdvanced";

const SETTINGS_KEY="new-eden-sage:pi-settings:v2";
const SAVED_KEY="new-eden-sage:pi-plans:v2";
const OBS_KEY="new-eden-sage:pi-observations:v2";
const ALERTS_KEY="new-eden-sage:pi-alerted:v2";
const NOTIFY_KEY="new-eden-sage:pi-notifications:v2";
const isk=new Intl.NumberFormat("en-GB",{maximumFractionDigits:0});
const compact=new Intl.NumberFormat("en-GB",{notation:"compact",maximumFractionDigits:2});
const number=new Intl.NumberFormat("en-GB",{maximumFractionDigits:1});

function stored<T>(key:string,fallback:T):T { try { const raw=localStorage.getItem(key); return raw?JSON.parse(raw) as T:fallback; } catch { return fallback; } }
function money(value:number|null|undefined,short=true){if(value==null||!Number.isFinite(value))return "—";return `${short?compact.format(value):isk.format(Math.round(value))} ISK`;}
function amount(value:number|null|undefined){return value==null||!Number.isFinite(value)?"—":number.format(value);}
function pct(value:number|null|undefined){return value==null||!Number.isFinite(value)?"—":`${value.toFixed(1)}%`;}
function duration(hours:number|null|undefined){if(hours==null||!Number.isFinite(hours))return "—";if(hours<1)return `${Math.max(1,Math.round(hours*60))}m`;if(hours<48)return `${hours.toFixed(hours<10?1:0)}h`;return `${(hours/24).toFixed(1)}d`;}
function when(value:string|null|undefined){if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString();}
function tierClass(tier:PlanetaryTier){return `pi-tier pi-tier-${tier.toLowerCase()}`;}
function healthClass(score:number){return score>=90?"good":score>=70?"watch":"bad";}

const DEFAULT_SETTINGS:PlanetaryRevenueSettings={pocoOwnerTaxPercent:0,brokerFeePercent:null,assumedSecurity:"high",cargoM3:10_000,haulingCostPerTripIsk:0,maxJumps:15,runtimeHours:24};

function TaxSettings({value,onChange,onApply}:{value:PlanetaryRevenueSettings;onChange:(next:PlanetaryRevenueSettings)=>void;onApply:()=>void}){
  return <div className="pi-assumptions">
    <label><span>POCO owner tax</span><div><input type="number" min={0} max={100} step={0.1} value={value.pocoOwnerTaxPercent??0} onChange={e=>onChange({...value,pocoOwnerTaxPercent:Number(e.target.value)||0})}/><b>%</b></div></label>
    <label><span>Security assumption</span><select value={value.assumedSecurity??"high"} onChange={e=>onChange({...value,assumedSecurity:e.target.value as PlanetarySecurityBand})}><option value="high">High-sec</option><option value="low">Low-sec</option><option value="null">Null / WH</option></select></label>
    <label><span>Broker fee override</span><div><input type="number" min={0} max={20} step={0.1} placeholder="Auto" value={value.brokerFeePercent??""} onChange={e=>onChange({...value,brokerFeePercent:e.target.value===""?null:Number(e.target.value)})}/><b>%</b></div></label>
    <label><span>Hauler cargo</span><div><input type="number" min={1} step={1000} value={value.cargoM3??10_000} onChange={e=>onChange({...value,cargoM3:Math.max(1,Number(e.target.value)||1)})}/><b>m³</b></div></label>
    <label><span>Hauling cost / trip</span><div><input type="number" min={0} step={100000} value={value.haulingCostPerTripIsk??0} onChange={e=>onChange({...value,haulingCostPerTripIsk:Math.max(0,Number(e.target.value)||0)})}/><b>ISK</b></div></label>
    <label><span>Finder radius</span><div><input type="number" min={0} max={100} value={value.maxJumps??15} onChange={e=>onChange({...value,maxJumps:Math.max(0,Number(e.target.value)||0)})}/><b>j</b></div></label>
    <label><span>Buffer runtime</span><div><input type="number" min={1} max={168} value={value.runtimeHours??24} onChange={e=>onChange({...value,runtimeHours:Math.max(1,Number(e.target.value)||1)})}/><b>h</b></div></label>
    <button onClick={onApply}>Apply assumptions</button>
  </div>;
}

function AlertRow({alert}:{alert:PlanetaryAlert}){
  const urgency=alert.severity==="critical"?"CRITICAL":alert.severity==="warning"?"WARNING":"ACTION SOON";
  return <div className={`pi-alert pi-alert-${alert.severity}`}><span className="pi-alert-dot"/><em className="pi-alert-urgency">{urgency}</em><div><strong>{alert.characterName} · {alert.planetLabel}</strong><span>{alert.message}</span></div>{alert.hoursUntil!=null&&<b>{duration(alert.hoursUntil)}</b>}</div>;
}

function ColonyCard({colony}:{colony:PlanetaryColonyAudit}){
  const [open,setOpen]=useState(false);
  return <article className={`pi-colony ${healthClass(colony.healthScore)}`}>
    <button className="pi-colony-head" onClick={()=>setOpen(!open)}>
      <div><span>{colony.characterName}</span><strong>{colony.solarSystemName} · {colony.planetType}</strong><small>{colony.regionName} · sec {colony.securityStatus.toFixed(1)} · ESI {when(colony.lastUpdate)}</small></div>
      <div className="pi-health"><b>{Math.round(colony.healthScore)}</b><span>HEALTH</span></div>
    </button>
    <div className="pi-colony-kpis">
      <span>Processors <b>{colony.processors}</b></span><span>Extractors <b>{colony.activeExtractors}</b></span><span>Next 24h extraction <b>{money(colony.extractorGrossPerDay)}</b></span><span>Configured net <b>{money(colony.configuredMarginCapacityPerDay)}</b></span><span>Stored <b>{money(colony.storageValue)}</b></span><span>Attention <b>{duration(colony.attentionHours)}</b></span>
    </div>
    {(colony.badRoutes+colony.starvedProcessors+colony.unroutedProcessors+colony.lowStockProcessors+colony.fullStorage)>0&&<div className="pi-colony-flags">
      {colony.starvedProcessors>0&&<span className="critical">{colony.starvedProcessors} starved</span>}{colony.badRoutes>0&&<span>{colony.badRoutes} broken routes</span>}{colony.unroutedProcessors>0&&<span>{colony.unroutedProcessors} outputs unrouted</span>}{colony.lowStockProcessors>0&&<span>{colony.lowStockProcessors} low buffers</span>}{colony.fullStorage>0&&<span>{colony.fullStorage} storage near full</span>}
    </div>}
    {open&&<div className="pi-colony-detail">
      <section><h6>Extractor programs</h6>{colony.extractors.length===0?<p>No extractor control units.</p>:colony.extractors.map((row,index)=><div className="pi-detail-row" key={`${row.productTypeId}-${index}`}><span>{row.productName??`Type ${row.productTypeId}`} · {row.heads} heads</span><b className={row.active?"":"negative"}>{row.active?`${duration(row.hoursUntilExpiry)} left`:"EXPIRED"}</b><small>{amount(row.next24hUnits)} next 24h · {money(row.grossNext24h)}{row.unrouted?" · OUTPUT UNROUTED":""}</small></div>)}</section>
      <section><h6>Processor feed health</h6>{colony.processorsHealth.length===0?<p>No configured processors.</p>:colony.processorsHealth.map(row=><div className="pi-detail-row" key={row.pinId}><span>{row.name}</span><b className={row.starving||row.unroutedOutput?"negative":"positive"}>{row.starving?"STARVED":row.unroutedOutput?"NO OUTPUT ROUTE":row.lowestHoursRemaining==null?"CONTINUOUS":`${duration(row.lowestHoursRemaining)} buffer`}</b><small>{row.inputs.map(input=>`${input.name}: ${input.starved?"no route":input.continuous?"continuous":duration(input.hoursRemaining)}`).join(" · ")}</small></div>)}</section>
      <section><h6>Storage</h6>{colony.storage.length===0?<p>No launchpad/storage contents exposed.</p>:colony.storage.map(row=><div className="pi-detail-row" key={row.pinId}><span>{row.name}</span><b className={row.fillPercent>=85?"negative":""}>{pct(row.fillPercent)}</b><small>{amount(row.usedM3)} / {amount(row.capacityM3)} m³{row.hoursToFull!=null?` · ${duration(row.hoursToFull)} to full`:""}</small></div>)}</section>
      <section><h6>Route validation</h6><div className="pi-route-summary"><b>{colony.routes.filter(row=>row.valid).length}</b> valid · <b>{colony.routes.filter(row=>!row.valid).length}</b> broken</div>{colony.routes.filter(row=>!row.valid).slice(0,8).map(row=><div className="pi-detail-row" key={row.routeId}><span>Route {row.routeId||"—"}</span><b className="negative">BROKEN</b><small>{row.issue}</small></div>)}</section>
    </div>}
  </article>;
}

function OpportunityTable({analysis,onPlan}:{analysis:PlanetaryRevenueAnalysis;onPlan:(row:PlanetaryFactoryOpportunity)=>void}){
  const [query,setQuery]=useState("");const [tier,setTier]=useState<"all"|PlanetaryTier>("all");const [profitable,setProfitable]=useState(true);
  const rows=useMemo(()=>analysis.opportunities.filter(row=>(tier==="all"||row.tier===tier)&&(!profitable||(row.taxAdjustedMarginPerDay??-1)>0)&&(!query.trim()||`${row.name} ${row.output.name} ${row.inputs.map(x=>x.name).join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()))).slice(0,150),[analysis,profitable,query,tier]);
  return <section className="pi-panel pi-opportunities"><div className="pi-panel-head"><div><span>MARKET INTELLIGENCE</span><h4>Factory opportunities</h4><p>Tax-adjusted profit ranked by executable retained market depth, not headline spread alone.</p></div><b>{rows.length} shown</b></div>
    <div className="pi-filterbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product or input…"/><select value={tier} onChange={e=>setTier(e.target.value as "all"|PlanetaryTier)}><option value="all">All tiers</option><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select><label><input type="checkbox" checked={profitable} onChange={e=>setProfitable(e.target.checked)}/> Profitable only</label></div>
    <div className="pi-table-wrap"><table><thead><tr><th>Product</th><th>Tax-adjusted net/day</th><th>ROI</th><th>Liquidity</th><th>Buy depth</th><th>POCO + haul/day</th><th>Market coverage</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.schematicId}><td><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.output.name}</strong><small>{amount(row.output.quantityPerDay)}/processor/day</small></td><td className={(row.taxAdjustedMarginPerDay??0)<0?"negative":"positive"}>{money(row.taxAdjustedMarginPerDay)}</td><td>{pct(row.marginPercent)}</td><td><div className="pi-meter"><i style={{width:`${Math.max(0,Math.min(100,row.liquidityScore))}%`}}/></div><small>{pct(row.liquidityScore)}</small></td><td>{row.buyDepthDays.toFixed(1)}d</td><td>{money(row.importTaxPerDay+row.exportTaxPerDay+row.haulingCostPerDay)}<small>haul {money(row.haulingCostPerDay)}</small></td><td>{pct(Math.min(row.inputCoveragePercent,row.outputCoveragePercent))}</td><td><button onClick={()=>onPlan(row)}>Plan</button></td></tr>)}</tbody></table></div>
  </section>;
}

function Operations({analysis,onPlan,notificationsEnabled,onToggleNotifications,onReload}:{analysis:PlanetaryRevenueAnalysis;onPlan:(row:PlanetaryFactoryOpportunity)=>void;notificationsEnabled:boolean;onToggleNotifications:()=>void;onReload:()=>void}){
  const [scope,setScope]=useState<string>("all");
  const scopeCharacter=scope==="all"?null:analysis.empire.characters.find(row=>row.characterId===scope)??null;
  const scopedColonies=scope==="all"?analysis.empire.colonies:analysis.empire.colonies.filter(row=>row.characterId===scope);
  const empireAlerts=scope==="all"?analysis.empire.alerts:analysis.empire.alerts.filter(row=>row.characterId===scope);
  const scopedHealth=scopedColonies.length?scopedColonies.reduce((sum,row)=>sum+row.healthScore,0)/scopedColonies.length:null;
  const scopedExtraction=scopedColonies.length&&scopedColonies.every(row=>row.extractorGrossPerDay!=null)?scopedColonies.reduce((sum,row)=>sum+Number(row.extractorGrossPerDay),0):null;
  const scopedStockpile=scope==="all"?analysis.stockpile:analysis.stockpile.filter(row=>scopeCharacter&&row.characters.includes(scopeCharacter.characterName));
  return <div className="pi-operations">
    <div className="pi-command-scope"><span>COMMAND SCOPE</span><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>All characters</button>{analysis.empire.characters.map(row=><button key={row.characterId} className={scope===row.characterId?"active":""} onClick={()=>setScope(row.characterId)}>{row.characterName}</button>)}</div>
    <div className="pi-kpis pi-kpis-6"><article><span>PI characters</span><strong>{scope==="all"?analysis.empire.totals.characters:1}</strong><small>{scopedColonies.length} colonies · {scopeCharacter?.spareColonies??analysis.empire.totals.spareColonies} slots free</small></article><article><span>Empire alerts</span><strong className={empireAlerts.length?"negative":"positive"}>{empireAlerts.length}</strong><small>{empireAlerts.filter(a=>a.severity==="critical").length} critical</small></article><article><span>Selected health</span><strong>{scopedHealth==null?"—":Math.round(scopedHealth)}</strong><small>route/feed/extractor/storage audit</small></article><article><span>Next 24h extraction</span><strong>{money(scopedExtraction)}</strong><small>CCP decay/noise forecast</small></article><article><span>Best liquid factory</span><strong>{money(analysis.summary.bestOpportunityMarginPerDay)}</strong><small>per processor/day after configured taxes</small></article><article><span>PI stockpile</span><strong>{scopedStockpile.length}</strong><small>commodity types across connected characters</small></article></div>

    <section className="pi-panel"><div className="pi-panel-head"><div><span>ATTENTION QUEUE</span><h4>What needs doing now</h4><p>Expired extractors, starving factories, broken routes, low buffers and storage pressure across every connected character.</p></div><button className={notificationsEnabled?"active":""} onClick={onToggleNotifications}>{notificationsEnabled?"Desktop alerts on":"Enable desktop alerts"}</button></div><div className="pi-attention-summary"><span className="critical">CRITICAL <b>{empireAlerts.filter(a=>a.severity==="critical").length}</b></span><span className="warning">WARNING <b>{empireAlerts.filter(a=>a.severity==="warning").length}</b></span><span className="soon">ACTION SOON <b>{empireAlerts.filter(a=>a.severity==="info").length}</b></span><span className="healthy">HEALTHY <b>{scopedColonies.filter(c=>c.status==="healthy").length}</b></span></div>{empireAlerts.length===0?<div className="pi-empty"><strong>No PI problems detected.</strong><span>When colonies are synced, operational issues land here in urgency order.</span></div>:<div className="pi-alert-list">{empireAlerts.slice(0,30).map(alert=><AlertRow key={alert.id} alert={alert}/>)}</div>}</section>

    <PlanetaryOptimizerPanel analysis={analysis} onReload={onReload}/>

    <section className="pi-panel"><div className="pi-panel-head"><div><span>EMPIRE VIEW</span><h4>Characters and planet capacity</h4><p>One view of the entire connected PI estate.</p></div></div><div className="pi-character-grid">{analysis.empire.characters.map(row=><article key={row.characterId}><strong>{row.characterName}</strong><span>{row.colonies} / {row.maxColonies} planets</span><small>{row.spareColonies} free · CCU {row.commandCenterUpgrades} · IC {row.interplanetaryConsolidation}</small><em>{row.systemName}</em></article>)}</div></section>

    <section className="pi-panel"><div className="pi-panel-head"><div><span>LIVE COLONY AUDIT</span><h4>Routes, buffers, storage and extractor programs</h4><p>Click a colony for pin-level operational diagnostics.</p></div><b>{scopedColonies.length} colonies</b></div>{scopedColonies.length===0?<div className="pi-empty"><strong>No connected character currently has a synced colony.</strong><span>The market scanner and full planner still work before you deploy your first command center.</span></div>:<div className="pi-colony-list">{scopedColonies.map(colony=><ColonyCard key={`${colony.characterId}:${colony.planetId}`} colony={colony}/>)}</div>}</section>

    <div className="pi-two-col">
      <section className="pi-panel"><div className="pi-panel-head"><div><span>STOCKPILE</span><h4>What you already own</h4><p>PI in character assets plus synced colony storage.</p></div></div>{analysis.stockpile.length===0?<div className="pi-empty"><span>No PI commodities found in connected data.</span></div>:<div className="pi-mini-list">{analysis.stockpile.slice(0,30).map(row=><div key={row.typeId}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b>{amount(row.quantity)}</b><small>{row.characters.join(", ")}</small></div>)}</div>}</section>
      <section className="pi-panel"><div className="pi-panel-head"><div><span>DOWNSTREAM DEMAND</span><h4>Active industry wants PI</h4><p>Base SDE material demand detected in connected active industry jobs.</p></div></div>{analysis.industryDemand.length===0?<div className="pi-empty"><span>No active industry job currently exposes a PI material requirement.</span></div>:<div className="pi-mini-list">{analysis.industryDemand.slice(0,30).map(row=><div key={row.typeId}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b>{amount(row.baseQuantity)}</b><small>{row.jobs} job signals · {row.characters.join(", ")}</small></div>)}</div>}</section>
    </div>
    <OpportunityTable analysis={analysis} onPlan={onPlan}/>
  </div>;
}

function LayoutCard({plan}:{plan:PlanetaryPlanResult}){const l=plan.layout;return <section className="pi-panel"><div className="pi-panel-head"><div><span>LAYOUT SIMULATOR</span><h4>{l.planetType} factory colony</h4><p>Deterministic CCP SDE facility loads are separated from radius-aware proposed-link estimates.</p></div><b className={l.fits?"pi-fit-ok":"pi-fit-bad"}>{l.fits?"FITS":"DOES NOT FIT"}</b></div><div className="pi-layout-bars"><div><span>CPU {amount(l.cpuUsed)} / {amount(l.cpuCapacity)}</span><div><i style={{width:`${l.cpuCapacity?Math.min(100,l.cpuUsed/l.cpuCapacity*100):100}%`}}/></div><small>{amount(l.cpuSpare)} spare</small></div><div><span>Power {amount(l.powerUsed)} / {amount(l.powerCapacity)}</span><div><i style={{width:`${l.powerCapacity?Math.min(100,l.powerUsed/l.powerCapacity*100):100}%`}}/></div><small>{amount(l.powerSpare)} spare</small></div></div><div className="pi-layout-meta"><span>{l.processors} processors</span><span>{l.launchpads} launchpad{l.launchpads===1?"":"s"}</span><span>Facilities CPU {amount(l.facilityCpuUsed)} · PG {amount(l.facilityPowerUsed)}</span><span>Estimated links CPU {amount(l.linkCpu)} · PG {amount(l.linkPower)}</span><span>{l.linkCount} compact links</span><span>{amount(l.minLinkKm)} km nominal minimum link</span><span>{amount(l.bufferVolumeM3)} m³ {l.runtimeHours}h buffer</span><span>CCU {l.ccuLevel}</span></div>{l.missingFacilities.length>0&&<div className="pi-warning">This planet type has no facility for: {l.missingFacilities.join(", ")}.</div>}</section>}

function Planner({analysis,snapshot,settings,onSettingsChange,onBack}:{analysis:PlanetaryRevenueAnalysis;snapshot:CharacterSnapshot;settings:PlanetaryRevenueSettings;onSettingsChange:(settings:PlanetaryRevenueSettings)=>void;onBack:()=>void}){
  const [productTypeId,setProductTypeId]=useState<number>(()=>analysis.opportunities.find(row=>(row.taxAdjustedMarginPerDay??0)>0)?.output.typeId??analysis.opportunities[0]?.output.typeId??0);
  const [finalProcessors,setFinalProcessors]=useState(1);const [mode,setMode]=useState<PlanetaryPlanMode>("full");const [hybridBuildTypeIds,setHybridBuildTypeIds]=useState<number[]|undefined>(undefined);const [finderSecurity,setFinderSecurity]=useState<"any"|PlanetarySecurityBand>("any");const [planetId,setPlanetId]=useState<number|null>(null);const [planetTypeId,setPlanetTypeId]=useState<number|null>(null);
  const [observations,setObservations]=useState<PlanetaryResourceObservation[]>([]);const [savedPlans,setSavedPlans]=useState<PlanetarySavedPlan[]>([]);const [loadedDesignerLayout,setLoadedDesignerLayout]=useState<PlanetarySavedPlan["designerLayout"]|null>(null);const [persistenceReady,setPersistenceReady]=useState(false);const [compareSaved,setCompareSaved]=useState<PlanetarySavedPlan|null>(null);const [plan,setPlan]=useState<PlanetaryPlanResult|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [templateText,setTemplateText]=useState("");const [observationText,setObservationText]=useState("");const [planName,setPlanName]=useState("");
  const selectedOpportunity=analysis.opportunities.find(row=>row.output.typeId===productTypeId)??analysis.opportunities[0];

  const planInput=useMemo<PlanetaryPlanInput>(()=>({characterId:snapshot.characterId,productTypeId:selectedOpportunity?.output.typeId??0,finalProcessors,mode,hybridBuildTypeIds,originSystemId:snapshot.location.solar_system_id,maxJumps:settings.maxJumps,finderSecurity,planetId,planetTypeId,resourceObservations:observations,pocoOwnerTaxPercent:settings.pocoOwnerTaxPercent,brokerFeePercent:settings.brokerFeePercent,assumedSecurity:settings.assumedSecurity,cargoM3:settings.cargoM3,runtimeHours:settings.runtimeHours}),[snapshot.characterId,snapshot.location.solar_system_id,selectedOpportunity?.output.typeId,finalProcessors,mode,hybridBuildTypeIds,settings,finderSecurity,planetId,planetTypeId,observations]);

  const calculate=useCallback(async()=>{if(!planInput.productTypeId)return;setLoading(true);setError("");try{setPlan(await window.sage.getPlanetaryPlan(planInput));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setLoading(false);}},[planInput]);
  useEffect(()=>{const timer=setTimeout(()=>void calculate(),220);return()=>clearTimeout(timer);},[calculate]);
  useEffect(()=>{let cancelled=false;void window.sage.getPlanetaryState().then(async state=>{if(cancelled)return;const legacyPlans=stored<PlanetarySavedPlan[]>(SAVED_KEY,[]);const legacyObservations=stored<PlanetaryResourceObservation[]>(OBS_KEY,[]);const plans=state.plans.length?state.plans:legacyPlans;const obs=state.observations.length?state.observations:legacyObservations;setSavedPlans(plans);setObservations(obs);setPersistenceReady(true);if(!state.plans.length&&legacyPlans.length){for(const saved of legacyPlans)await window.sage.savePlanetaryPlan(saved);localStorage.removeItem(SAVED_KEY);}if(!state.observations.length&&legacyObservations.length){await window.sage.savePlanetaryObservations(legacyObservations);localStorage.removeItem(OBS_KEY);}}).catch(value=>{if(!cancelled){setPersistenceReady(true);setError(`PI persistence failed: ${value instanceof Error?value.message:String(value)}`);}});return()=>{cancelled=true;};},[]);
  useEffect(()=>{if(!persistenceReady)return;const timer=setTimeout(()=>{void window.sage.savePlanetaryObservations(observations).catch(value=>setError(`Saving observations failed: ${value instanceof Error?value.message:String(value)}`));},180);return()=>clearTimeout(timer);},[observations,persistenceReady]);

  const toggleHybrid=(typeId:number)=>setHybridBuildTypeIds(current=>{const base=current??plan?.recommendedHybridBuildTypeIds??[];return base.includes(typeId)?base.filter(id=>id!==typeId):[...base,typeId];});
  const choosePlanet=(row:PlanetaryPlanResult["systemFinder"]["planets"][number])=>{setPlanetId(row.planetId);setPlanetTypeId(row.planetTypeId);};
  const recordDensity=(planet:number,score:number)=>setObservations(current=>[...current.filter(row=>row.planetId!==planet||row.resourceTypeId!=null),{planetId:planet,score,characterId:String(snapshot.characterId),observedAt:new Date().toISOString()}]);
  const importObservations=()=>{try{const text=observationText.trim();if(!text)return;let next:PlanetaryResourceObservation[]=[];if(text.startsWith("[")||text.startsWith("{")){const parsed=JSON.parse(text);next=Array.isArray(parsed)?parsed:[parsed];}else next=text.split(/\r?\n/).filter(Boolean).map(line=>{const [planet,resource,percent,note]=line.split(",").map(x=>x.trim());return {planetId:Number(planet),resourceName:resource||undefined,percent:Number(percent),note};});next=next.filter(row=>Number(row.planetId)>0&&Number.isFinite(Number(row.percent))&&Number(row.percent)>=0&&Number(row.percent)<=100).map(row=>({...row,characterId:row.characterId??String(snapshot.characterId),characterName:row.characterName??snapshot.character?.name,source:row.source??"import",confidence:row.confidence??0.7,scope:row.scope??"personal",observedAt:row.observedAt??new Date().toISOString()}));setObservations(current=>[...current,...next]);setObservationText("");}catch(value){setError(`Density import failed: ${value instanceof Error?value.message:String(value)}`);}};
  const importTemplate=()=>{try{const parsed=JSON.parse(templateText);const schematics=(Array.isArray(parsed?.P)?parsed.P:[]).map((pin:any)=>Number(pin?.S??0)).filter(Boolean);const counts=new Map<number,number>();for(const id of schematics)counts.set(id,(counts.get(id)??0)+1);const selected=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0];if(!selected)throw new Error("No factory schematic pins found.");const opportunity=analysis.opportunities.find(row=>row.output.typeId===selected[0]);if(!opportunity)throw new Error(`Template product ${selected[0]} is not a current PI recipe.`);setProductTypeId(opportunity.output.typeId);setFinalProcessors(selected[1]);setPlanetTypeId(Number(parsed.Pln)||null);setPlanetId(null);setMode("buy");setHybridBuildTypeIds([]);setTemplateText("");}catch(value){setError(`Template import failed: ${value instanceof Error?value.message:String(value)}`);}};
  const savePlan=async()=>{const name=planName.trim()||`${plan?.target.name??selectedOpportunity?.output.name??"PI plan"} · ${mode}`;const saved:PlanetarySavedPlan={id:`${Date.now()}`,name,savedAt:new Date().toISOString(),input:planInput};try{const persisted=await window.sage.savePlanetaryPlan(saved);setSavedPlans(current=>[persisted,...current.filter(row=>row.id!==persisted.id)].slice(0,50));setPlanName("");}catch(value){setError(`Saving plan failed: ${value instanceof Error?value.message:String(value)}`);}};
  const deleteSaved=async(saved:PlanetarySavedPlan)=>{try{await window.sage.deletePlanetaryPlan(saved.id);setSavedPlans(current=>current.filter(row=>row.id!==saved.id));if(compareSaved?.id===saved.id)setCompareSaved(null);}catch(value){setError(`Deleting plan failed: ${value instanceof Error?value.message:String(value)}`);}};
  const cloneSaved=async(saved:PlanetarySavedPlan)=>{const clone:PlanetarySavedPlan={...saved,id:`${Date.now()}`,name:`${saved.name} copy`,savedAt:new Date().toISOString()};try{const persisted=await window.sage.savePlanetaryPlan(clone);setSavedPlans(current=>[persisted,...current]);}catch(value){setError(`Cloning plan failed: ${value instanceof Error?value.message:String(value)}`);}};
  const renameSaved=async(saved:PlanetarySavedPlan)=>{const name=window.prompt("Rename PI plan",saved.name)?.trim();if(!name||name===saved.name)return;try{const persisted=await window.sage.savePlanetaryPlan({...saved,name});setSavedPlans(current=>current.map(row=>row.id===saved.id?persisted:row));}catch(value){setError(`Renaming plan failed: ${value instanceof Error?value.message:String(value)}`);}};
  const loadSaved=(saved:PlanetarySavedPlan)=>{const input=saved.input;setLoadedDesignerLayout(saved.designerLayout??null);setProductTypeId(input.productTypeId);setFinalProcessors(input.finalProcessors??1);setMode(input.mode??"full");setHybridBuildTypeIds(input.hybridBuildTypeIds);setFinderSecurity(input.finderSecurity??"any");setPlanetId(input.planetId??null);setPlanetTypeId(input.planetTypeId??null);onSettingsChange({...settings,pocoOwnerTaxPercent:input.pocoOwnerTaxPercent??settings.pocoOwnerTaxPercent,brokerFeePercent:input.brokerFeePercent??settings.brokerFeePercent,assumedSecurity:input.assumedSecurity??settings.assumedSecurity,cargoM3:input.cargoM3??settings.cargoM3,haulingCostPerTripIsk:input.haulingCostPerTripIsk??settings.haulingCostPerTripIsk,maxJumps:input.maxJumps??settings.maxJumps,runtimeHours:input.runtimeHours??settings.runtimeHours});};

  if(!selectedOpportunity)return <div className="pi-empty"><strong>No PI schematic is available.</strong></div>;
  return <div className="pi-planner">
    <section className="pi-planner-hero"><div><span>PLANETARY PLANNER</span><h4>Design the entire PI operation</h4><p>Build/buy/extract decisions, stockpile refills, character allocation, planet search, layout fitting, hauling and EVE template output in one plan.</p></div><button onClick={onBack}>← Planetary Command</button></section>
    <div className="pi-planner-controls">
      <label className="wide"><span>Target product</span><select value={selectedOpportunity.output.typeId} onChange={e=>{setProductTypeId(Number(e.target.value));setPlanetId(null);setPlanetTypeId(null);setHybridBuildTypeIds(undefined);}}>{analysis.opportunities.filter(row=>row.tier!=="P0").sort((a,b)=>(b.taxAdjustedMarginPerDay??-Infinity)-(a.taxAdjustedMarginPerDay??-Infinity)).map(row=><option key={row.schematicId} value={row.output.typeId}>{row.tier} · {row.output.name} · {money(row.taxAdjustedMarginPerDay)}/processor/day</option>)}</select></label>
      <label><span>Final processors</span><input type="number" min={1} max={40} value={finalProcessors} onChange={e=>setFinalProcessors(Math.max(1,Math.min(40,Number(e.target.value)||1)))}/></label>
      <label><span>Production model</span><select value={mode} onChange={e=>{setMode(e.target.value as PlanetaryPlanMode);setHybridBuildTypeIds(undefined);}}><option value="buy">Buy inputs</option><option value="full">Full P0→target chain</option><option value="hybrid">Hybrid optimiser</option></select></label>
      <label><span>Finder security</span><select value={finderSecurity} onChange={e=>setFinderSecurity(e.target.value as "any"|PlanetarySecurityBand)}><option value="any">Any security</option><option value="high">High-sec only</option><option value="low">Low-sec only</option><option value="null">Null / WH only</option></select></label>
      <button onClick={()=>void calculate()} disabled={loading}>{loading?"Calculating…":"Recalculate"}</button>
    </div>
    {error&&<div className="pi-error">{error}</div>}
    {!plan?<div className="pi-loading">Building planetary plan…</div>:<>
      <div className="pi-kpis pi-kpis-6"><article><span>Output/day</span><strong>{amount(plan.target.outputPerDay)}</strong><small>{plan.target.name}</small></article><article><span>Immediate net/day</span><strong className={(plan.target.taxAdjustedProfitPerDay??0)>=0?"positive":"negative"}>{money(plan.target.taxAdjustedProfitPerDay)}</strong><small>chosen-chain true net</small></article><article><span>Sell-order net/day</span><strong>{money(plan.target.sellOrderProfitPerDay)}</strong><small>chosen-chain net after broker + sales tax</small></article><article><span>Liquidity</span><strong>{pct(plan.target.liquidityScore)}</strong><small>{plan.target.buyDepthDays.toFixed(1)} days retained buy depth</small></article><article><span>Processors</span><strong>{plan.chain.dedicatedProcessors}</strong><small>{amount(plan.chain.processorEquivalent)} continuous equivalents</small></article><article><span>Stockpile runtime</span><strong>{duration(plan.stockpileRuntimeHours)}</strong><small>{plan.stockpileBuildable?`${amount(plan.stockpileBuildable.outputUnits)} direct output buildable`:"source-input coverage"}</small></article></div>

      <PlanetaryBasketPlanner analysis={analysis} snapshot={snapshot} settings={settings} observations={observations}/>

      <section className="pi-panel pi-economics"><div className="pi-panel-head"><div><span>TRUE PLAN ECONOMICS</span><h4>Chosen chain cost stack</h4><p>Repriced from the plan's actual external inputs, POCO movement, character market fees and your hauling-cost assumption.</p></div><b className={(plan.target.taxAdjustedProfitPerDay??0)>=0?"positive":"negative"}>{pct(plan.target.trueMarginPercent)} margin</b></div><div className="pi-stat-list pi-stat-grid"><span>Gross immediate <b>{money(plan.target.immediateRevenuePerDay)}</b></span><span>Input acquisition <b>{money(plan.target.inputAcquisitionCostPerDay)}</b></span><span>POCO import <b>{money(plan.target.importTaxPerDay)}</b></span><span>POCO export <b>{money(plan.target.exportTaxPerDay)}</b></span><span>Market fees <b>{money(plan.target.marketFeesPerDay)}</b></span><span>Hauling <b>{money(plan.target.haulingCostPerDay)}</b></span><span>TRUE net/day <b>{money(plan.target.taxAdjustedProfitPerDay)}</b></span><span>TRUE margin <b>{pct(plan.target.trueMarginPercent)}</b></span></div></section>

      <section className="pi-panel"><div className="pi-panel-head"><div><span>SOURCE STRATEGY</span><h4>Buy / extract / produce</h4><p>Every material in the selected chain has an explicit source decision; P0 extraction is only assumed outside Buy Inputs mode.</p></div></div><div className="pi-source-grid">{plan.sourceDecisions.map((row,index)=><article key={`${row.decision}-${row.typeId}-${index}`} className={`decision-${row.decision.toLowerCase()}`}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b>{row.decision}</b><small>{amount(row.quantityPerDay)}/day · {row.reason}</small></article>)}</div></section>

      {mode==="hybrid"&&<section className="pi-panel"><div className="pi-panel-head"><div><span>HYBRID OPTIMISER</span><h4>Choose what Sage manufactures vs buys</h4><p>Recommendations prefer intermediates currently cheaper to manufacture than to buy. Override any tier.</p></div></div>{(plan as PlanetaryPlanResult&{hybridCandidates?:Array<{typeId:number;name:string;tier:PlanetaryTier;recommended:boolean}>}).hybridCandidates?.length?<div className="pi-hybrid-grid">{(plan as PlanetaryPlanResult&{hybridCandidates:Array<{typeId:number;name:string;tier:PlanetaryTier;recommended:boolean}>}).hybridCandidates.map(row=>{const active=(hybridBuildTypeIds??plan.recommendedHybridBuildTypeIds).includes(row.typeId);return <button key={row.typeId} className={active?"active":""} onClick={()=>toggleHybrid(row.typeId)}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b>{active?"BUILD":"BUY"}</b>{row.recommended&&<small>Sage recommendation</small>}</button>;})}</div>:<div className="pi-empty"><span>No intermediate choice exists for this target.</span></div>}</section>}

      <div className="pi-two-col">
        <section className="pi-panel"><div className="pi-panel-head"><div><span>PRODUCTION CHAIN</span><h4>Continuous processors</h4><p>Every built stage sized to sustain the selected final processors.</p></div></div><div className="pi-chain-list">{plan.chain.processors.map(row=><div key={row.schematicId}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.outputName}</strong><b>{amount(row.equivalent)} eq · {row.dedicated} dedicated</b><small>{row.inputs.map(input=>`${amount(input.quantityPerDay*row.equivalent)} ${input.name}/day`).join(" · ")}</small></div>)}</div></section>
        <section className="pi-panel"><div className="pi-panel-head"><div><span>REFILL PLANNER</span><h4>{settings.runtimeHours??24}h external-input load</h4><p>Empire stockpile is applied before Sage tells you what to acquire or extract.</p></div></div>{plan.refill.length===0?<div className="pi-empty"><strong>Self-contained chain.</strong><span>No external commodity input remains above P0.</span></div>:<div className="pi-chain-list">{plan.refill.map(row=><div key={row.typeId}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b className={row.shortage>0?"negative":"positive"}>{row.shortage>0?`${amount(row.shortage)} short`:"COVERED"}</b><small>Need {amount(row.need)} · have {amount(row.have)} · {amount(row.shortageVolumeM3)} m³ shortfall</small></div>)}</div>}</section>
      </div>

      <LayoutCard plan={plan}/>
      <PlanetaryDesigner plan={plan} snapshot={snapshot} currentInput={planInput} initialLayout={loadedDesignerLayout} onTemplateSaved={saved=>setSavedPlans(current=>[saved,...current.filter(row=>row.id!==saved.id)])}/>

      <section className="pi-panel"><div className="pi-panel-head"><div><span>CHARACTER ALLOCATION</span><h4>Who should run which planets</h4><p>Greedy minimum planet-type coverage for the required P0 resources, allocated across every free connected colony slot.</p></div><b className={plan.allocation.deficit?"negative":"positive"}>{plan.allocation.deficit?`${plan.allocation.deficit} planets short`:`${plan.allocation.availableColonies} slots available`}</b></div><div className="pi-allocation-grid">{plan.allocation.assignments.map((row,index)=><article key={`${row.role}-${index}`} className={row.assigned?"":"unassigned"}><span>{row.role}</span><strong>{row.characterName??"NO FREE CHARACTER SLOT"}</strong><p>{row.detail}</p><small>{row.planetType??plan.layout.planetType}{row.ccuLevel!=null?` · CCU ${row.ccuLevel}`:""}</small></article>)}</div></section>

      <section className="pi-panel"><div className="pi-panel-head"><div><span>SYSTEM / PLANET FINDER</span><h4>Where this chain can live</h4><p>Compatibility is exact by planet type. Per-resource richness is only shown when you or your corporation recorded it; incomplete evidence remains UNKNOWN.</p></div><b>{plan.systemFinder.systems.length} systems</b></div>
        <div className="pi-finder-grid"><div><h6>Best systems from {snapshot.location.solar_system_name}</h6><div className="pi-finder-list">{plan.systemFinder.systems.slice(0,20).map(row=><div key={row.systemId}><strong>{row.systemName}</strong><span>{row.regionName} · {row.securityStatus.toFixed(1)}</span><b>{row.jumps}j · {pct(row.coveragePercent)}</b><small>{row.coveredResources.map(r=>r.name).join(", ")||"Factory-only plan"}</small></div>)}</div></div><div><h6>Best planets</h6><div className="pi-finder-list">{plan.systemFinder.planets.slice(0,25).map(row=><div key={row.planetId} className={planetId===row.planetId?"selected":""}><strong>{row.systemName} {row.planetIndex?`P${row.planetIndex}`:""} · {row.planetType}</strong><span>{row.jumps}j · radius {amount(row.radiusKm)} km · density {row.densityBottleneckPercent==null?"UNKNOWN":`${row.densityBottleneckPercent.toFixed(0)}% bottleneck`}</span><b>{pct(row.coveragePercent)}</b><small>{row.resources.map(r=>r.name).join(", ")||"Factory compatible"}</small><div className="pi-finder-actions"><button onClick={()=>choosePlanet(row)}>Use planet</button><span>{row.densityKnownPercent==null?"":`${row.densityKnownPercent.toFixed(0)}% evidence`}</span></div></div>)}</div></div></div>
      </section>

      <PlanetarySurveyPanel plan={plan} snapshot={snapshot} observations={observations} setObservations={setObservations}/>

      <div className="pi-two-col">
        <section className="pi-panel"><div className="pi-panel-head"><div><span>HAULING CADENCE</span><h4>{amount(plan.hauling.totalM3PerDay)} m³/day</h4><p>Exact commodity volume turned into trips for your configured cargo capacity.</p></div></div><div className="pi-stat-list"><span>Inbound/day <b>{amount(plan.hauling.inboundM3PerDay)} m³</b></span><span>Outbound/day <b>{amount(plan.hauling.outboundM3PerDay)} m³</b></span><span>Trips/day avg <b>{amount(plan.hauling.tripsPerDay)}</b></span><span>Trips/week <b>{plan.hauling.tripsPerWeek}</b></span><span>Cost/trip <b>{money(plan.hauling.costPerTripIsk)}</b></span><span>Hauling/week <b>{money(plan.hauling.costPerWeek)}</b></span><span>Best finder system <b>{plan.hauling.jumpsOneWay==null?"—":`${plan.hauling.jumpsOneWay} jumps`}</b></span><span>Weekly gate legs <b>{plan.hauling.jumpLegsPerWeek??"—"}</b></span></div><small>{plan.hauling.basis}</small></section>
        <section className="pi-panel"><div className="pi-panel-head"><div><span>INDUSTRY LINK</span><h4>Downstream demand</h4><p>Active connected manufacturing jobs consuming this plan's PI products.</p></div></div>{plan.industryDemand.length===0?<div className="pi-empty"><span>No active job currently demands this chain.</span></div>:<div className="pi-mini-list">{plan.industryDemand.map(row=><div key={row.typeId}><span className={tierClass(row.tier)}>{row.tier}</span><strong>{row.name}</strong><b>{amount(row.baseQuantity)}</b><small>{row.jobs} job signals</small></div>)}</div>}</section>
      </div>

      <div className="pi-two-col">
        <section className="pi-panel"><div className="pi-panel-head"><div><span>EVE TEMPLATE</span><h4>Import / export colony templates</h4><p>Sage emits the current EVE PI JSON schema: pins, links, routes, schematics, planet and CCU.</p></div>{plan.eveTemplate&&<button onClick={()=>void window.sage.copyText(JSON.stringify(plan.eveTemplate))}>Copy EVE template</button>}</div>{plan.eveTemplate?<pre className="pi-template-preview">{JSON.stringify(plan.eveTemplate,null,2).slice(0,4000)}{JSON.stringify(plan.eveTemplate).length>4000?"\n…":""}</pre>:<div className="pi-empty"><strong>No valid template yet.</strong><span>The selected simulated layout must fit before Sage exports it.</span></div>}<textarea value={templateText} onChange={e=>setTemplateText(e.target.value)} placeholder="Paste an EVE PI template JSON here to load its target, planet type and factory count…"/><button onClick={importTemplate} disabled={!templateText.trim()}>Load pasted template</button></section>
        <section className="pi-panel"><div className="pi-panel-head"><div><span>DENSITY OBSERVATIONS</span><h4>Local resource evidence</h4><p>ESI cannot expose real planet richness. Record it yourself or import corp observations without pretending it came from CCP.</p></div><button onClick={()=>void window.sage.copyText(JSON.stringify(observations,null,2))}>Copy observations</button></div><textarea value={observationText} onChange={e=>setObservationText(e.target.value)} placeholder={'CSV: planetId, resource name, observed percentage 0-100, note\nOr paste Sage observation JSON'}/><div className="pi-inline-actions"><button onClick={importObservations} disabled={!observationText.trim()}>Import observations</button><button onClick={()=>setObservations([])} disabled={!observations.length}>Clear saved observations</button><b>{observations.length} records</b></div></section>
      </div>

      <PlanetaryTemplateLibrary snapshot={snapshot} currentInput={planInput} savedPlans={savedPlans} setSavedPlans={setSavedPlans} onLoad={loadSaved}/>

      <section className="pi-panel"><div className="pi-panel-head"><div><span>SAVED PLANS</span><h4>Profiles and sharing</h4><p>Keep alternate factory, extraction and hybrid setups locally; share the exact planner input as JSON.</p></div><button onClick={()=>void window.sage.copyText(JSON.stringify(planInput,null,2))}>Copy current plan</button></div><div className="pi-savebar"><input value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="Plan name (optional)"/><button onClick={savePlan}>Save current plan</button></div>{compareSaved&&<div className="pi-plan-compare"><strong>Comparing current plan with {compareSaved.name}</strong><span>Product {compareSaved.input.productTypeId===planInput.productTypeId?"same":"different"} · mode {compareSaved.input.mode??"full"} → {planInput.mode??"full"} · processors {compareSaved.input.finalProcessors??1} → {planInput.finalProcessors??1} · max jumps {compareSaved.input.maxJumps??15} → {planInput.maxJumps??15} · POCO {compareSaved.input.pocoOwnerTaxPercent??0}% → {planInput.pocoOwnerTaxPercent??0}%</span></div>}{savedPlans.length===0?<div className="pi-empty"><span>No saved PI plans yet.</span></div>:<div className="pi-saved-list">{savedPlans.map(saved=><div key={saved.id}><strong>{saved.name}</strong><span>{when(saved.savedAt)}</span><div><button onClick={()=>loadSaved(saved)}>Load</button><button onClick={()=>setCompareSaved(compareSaved?.id===saved.id?null:saved)}>{compareSaved?.id===saved.id?"Close compare":"Compare"}</button><button onClick={()=>void cloneSaved(saved)}>Clone</button><button onClick={()=>void renameSaved(saved)}>Rename</button><button onClick={()=>void window.sage.copyText(JSON.stringify(saved.input,null,2))}>Share</button><button onClick={()=>void deleteSaved(saved)}>Delete</button></div></div>)}</div>}</section>
    </>}
  </div>;
}

export function PlanetaryRevenue({snapshot,marketDataRevision=0}:{snapshot:CharacterSnapshot;marketDataRevision?:number}){
  const [subtab,setSubtab]=useState<"analysis"|"helper">("analysis");const [settings,setSettings]=useState<PlanetaryRevenueSettings>(()=>({...DEFAULT_SETTINGS,...stored(SETTINGS_KEY,DEFAULT_SETTINGS)}));const [draftSettings,setDraftSettings]=useState<PlanetaryRevenueSettings>(settings);const [analysis,setAnalysis]=useState<PlanetaryRevenueAnalysis|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notificationsEnabled,setNotificationsEnabled]=useState(()=>stored<boolean>(NOTIFY_KEY,false));const [plannerSeed,setPlannerSeed]=useState<number|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{setAnalysis(await window.sage.getPlanetaryRevenue({characterId:snapshot.characterId,settings}));}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setLoading(false);}},[snapshot.characterId,settings]);
  useEffect(()=>{void load();},[load,snapshot.updatedAt,marketDataRevision]);
  useEffect(()=>{if(!analysis||!notificationsEnabled||typeof Notification==="undefined"||Notification.permission!=="granted")return;const seen=new Set(stored<string[]>(ALERTS_KEY,[]));const fresh=analysis.empire.alerts.filter(alert=>!seen.has(alert.id)&&alert.severity!=="info").slice(0,8);for(const alert of fresh)new Notification(`New Eden Sage · PI ${alert.severity}`,{body:`${alert.characterName} · ${alert.planetLabel}: ${alert.message}`});const next=[...new Set([...seen,...analysis.empire.alerts.map(alert=>alert.id)])].slice(-500);localStorage.setItem(ALERTS_KEY,JSON.stringify(next));},[analysis,notificationsEnabled]);
  const applySettings=()=>{const next={...DEFAULT_SETTINGS,...draftSettings};localStorage.setItem(SETTINGS_KEY,JSON.stringify(next));setSettings(next);};
  const updatePlannerSettings=(next:PlanetaryRevenueSettings)=>{setSettings(next);setDraftSettings(next);localStorage.setItem(SETTINGS_KEY,JSON.stringify(next));};
  const toggleNotifications=async()=>{if(notificationsEnabled){setNotificationsEnabled(false);localStorage.setItem(NOTIFY_KEY,"false");return;}if(typeof Notification==="undefined"){setError("Desktop notifications are unavailable in this renderer.");return;}const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission==="granted"){setNotificationsEnabled(true);localStorage.setItem(NOTIFY_KEY,"true");}else setError("Desktop notification permission was not granted.");};
  const openPlanner=(row:PlanetaryFactoryOpportunity)=>{setPlannerSeed(row.output.typeId);setSubtab("helper");};
  if(loading&&!analysis)return <div className="pi-loading">Building PI operations intelligence from CCP data, colonies and retained market depth…</div>;
  if(error&&!analysis)return <div className="pi-error">Planetary Revenue failed: {error} <button onClick={()=>void load()}>Retry</button></div>;
  if(!analysis)return null;
  return <section className="planetary-revenue-v2">
    <header className="pi-head"><div><span>PLANETARY REVENUE</span><h3>Planetary Command & Planning</h3><p>Run the colonies you already have, then design the next ones from market to planet to hauling route.</p></div><div className="pi-head-meta"><span>Market snapshot <b>{when(analysis.marketCreatedAt)}</b></span><span>Generated <b>{when(analysis.generatedAt)}</b></span><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div></header>
    <div className="pi-tabs"><button className={subtab==="analysis"?"active":""} onClick={()=>setSubtab("analysis")}><strong>Planetary Command</strong><span>Live empire health + market intelligence</span></button><button className={subtab==="helper"?"active":""} onClick={()=>setSubtab("helper")}><strong>Planetary Planner</strong><span>Production, allocation, finder + EVE templates</span></button></div>
    <TaxSettings value={draftSettings} onChange={setDraftSettings} onApply={applySettings}/>
    <div className="pi-tax-strip"><span>Accounting <b>{analysis.settings.accountingLevel}</b></span><span>Sales tax <b>{analysis.settings.salesTaxPercent.toFixed(2)}%</b></span><span>Broker Relations <b>{analysis.settings.brokerRelationsLevel}</b></span><span>Broker estimate <b>{analysis.settings.brokerFeePercent.toFixed(2)}%</b></span><span>Customs Code Expertise <b>{analysis.settings.customsCodeExpertiseLevel}</b></span><span>Effective POCO assumption <b>{analysis.settings.pocoTaxPercent.toFixed(1)}%</b></span></div>
    {error&&<div className="pi-error inline">{error}</div>}
    {subtab==="analysis"?<Operations analysis={analysis} onPlan={openPlanner} notificationsEnabled={notificationsEnabled} onToggleNotifications={()=>void toggleNotifications()} onReload={()=>void load()}/>:<Planner key={`${snapshot.characterId}:${plannerSeed??"default"}`} analysis={plannerSeed?{...analysis,opportunities:[...analysis.opportunities].sort((a,b)=>Number(b.output.typeId===plannerSeed)-Number(a.output.typeId===plannerSeed))}:analysis} snapshot={snapshot} settings={settings} onSettingsChange={updatePlannerSettings} onBack={()=>setSubtab("analysis")}/>}
    <div className="pi-notes">{analysis.notes.map(note=><span key={note}>{note}</span>)}</div>
  </section>;
}
