import type { WargameDamageSource, WargameMovementOrder, WargameOrderStep, WargamePropulsionOrder } from "./wargame-command-model";

export type WargameSupportSystem = {
  typeId: number;
  name: string;
  groupId: number;
  quantity: number;
  state?: string;
  kind: string;
  cycleSeconds: number;
  optimalM: number;
  falloffM: number;
  chargeTypeId?: number;
  amountPerCycle?: number;
  perSecond?: number;
  strength?: number;
  warpStrength?: number;
  mwdShutdown?: boolean;
  signatureBonus?: number;
  maxTargetRangeBonus?: number;
  scanResolutionBonus?: number;
  sensorStrengthBonus?: number;
  optimalBonus?: number;
  falloffBonus?: number;
  trackingBonus?: number;
  sensorStrengths?: number[];
  buffs?: Array<{ buffId: number; description: string; value: number }>;
  sourceKind?: string;
  ancillary?: boolean;
  mutadaptive?: boolean;
  charged?: boolean;
  chargedCycles?: number;
  baseAmountPerCycle?: number;
  burstPerSecond?: number;
  sustainedPerSecond?: number;
  unchargedPerSecond?: number;
  chargedMultiplier?: number;
  rampPerCycle?: number;
  maxMultiplier?: number;
  maxAmountPerCycle?: number;
  maxPerSecond?: number;
  cyclesToMax?: number;
  secondsToMax?: number;
  magazine?: { cyclesLoaded?:number; cyclesPerMagazine?:number; reloadSeconds?:number; explicitLoadedState?:boolean; [key:string]:unknown };
  loadedCyclesRemaining?: number;
  magazineCycles?: number;
  reloadSeconds?: number;
  reloadRemaining?: number;
  spoolCycles?: number;
  spoolTargetId?: string;
  fighterCount?: number;
  squadronSize?: number;
  independentFighterRolls?: number;
  fighterAbility?: string;
  fighterCountInitial?: number;
  fighterCountRemaining?: number;
  fighterMaximumVelocityMps?: number;
  fighterOrbitRangeM?: number;
  perFighterStrength?: number;
  activeRemaining?: number;
  activeTargetId?: string;
  fighterOnTargetId?: string;
  fighterArrivalRemaining?: number;
};

export type WargameSide = "blue" | "red";
export type WargameWeaponModel = "turret" | "missile" | "drone" | "support";
export type WargameStance = "brawl" | "pursue" | "kite" | "screen" | "support" | "hold";
export type WargameMovementState = "idle" | "approaching" | "orbiting" | "keeping-range" | "anchoring" | "aligning" | "aligned" | "warping" | "landed" | "disengaging";

export type WargameInterdictionZone = {
  id: string;
  label: string;
  x: number;
  y: number;
  radiusKm: number;
  sourceUnitId?: string;
};

export type WargameUnit = {
  id: string;
  name: string;
  typeId?: number;
  side: WargameSide;
  count: number;
  x: number;
  y: number;
  dps: number;
  ehp: number;
  speed: number;
  range: number;
  em: number;
  therm: number;
  kin: number;
  exp: number;
  role: string;
  targetId?: string;
  maxEhp?: number;
  destinationX?: number;
  destinationY?: number;
  weaponModel?: WargameWeaponModel;
  signature?: number;
  tracking?: number;
  repPerSecond?: number;
  repRange?: number;
  webStrength?: number;
  webRange?: number;
  tackleRange?: number;
  stance?: WargameStance;
  velocityX?: number;
  velocityY?: number;
  effectiveSpeed?: number;
  application?: number;
  repTargetId?: string;
  shipsAlive?: number;
  primaryEhp?: number;
  primaryShieldHp?: number;
  primaryArmorHp?: number;
  primaryStructureHp?: number;
  weaponCycle?: number;
  fireCooldown?: number;
  targetSwitchDelay?: number;
  lockRemaining?: number;
  lastTargetId?: string;
  repCycle?: number;
  repCooldown?: number;
  repLockTime?: number;
  repLockRemaining?: number;
  repLastTargetId?: string;
  lastVolleyDamage?: number;
  volleyPerShip?: number;
  optimalRange?: number;
  falloffRange?: number;
  signatureResolution?: number;
  explosionRadius?: number;
  explosionVelocity?: number;
  damageReductionFactor?: number;
  damageEm?: number;
  damageTherm?: number;
  damageKin?: number;
  damageExp?: number;
  shieldHp?: number;
  armorHp?: number;
  structureHp?: number;
  shieldResists?: [number, number, number, number];
  armorResists?: [number, number, number, number];
  hullResists?: [number, number, number, number];
  fitName?: string;
  fitCharacter?: string;
  fitSourceSummary?: string;
  simulationReady?: boolean;
  supportSystems?: WargameSupportSystem[];
  capacitorCapacity?: number;
  capacitorCurrent?: number;
  capacitorRechargeSeconds?: number;
  capacitorDemandGjPerSecond?: number;
  capacitorInjectedGjPerSecond?: number;
  baseSpeed?: number;
  propulsionKind?: "ab" | "mwd";
  targetingRange?: number;
  scanResolution?: number;
  sensorStrength?: number;
  ewarSignatureMultiplier?: number;
  ewarTrackingMultiplier?: number;
  ewarOptimalMultiplier?: number;
  ewarFalloffMultiplier?: number;
  ewarTargetingRangeMultiplier?: number;
  ewarScanResolutionMultiplier?: number;
  jamRemaining?: number;
  jammedBy?: string;
  scrammed?: boolean;
  neutPressureGjPerSecond?: number;
  supportCooldowns?: Record<string, number>;
  supportTargetIds?: Record<string, string | undefined>;
  supportLastTargetIds?: Record<string, string | undefined>;
  supportLockRemaining?: Record<string, number>;
  damageSources?: WargameDamageSource[];
  fitText?: string;
  orderChain?: WargameOrderStep[];
  activeOrderIndex?: number;
  activeOrderStartedAt?: number;
  activeOrderElapsed?: number;
  activeOrderWaitElapsed?: number;
  activeOrderStarted?: boolean;
  movementPropulsion?: WargamePropulsionOrder;
  movementOrder?: WargameMovementOrder;
  movementState?: WargameMovementState;
  movementTargetId?: string;
  movementRangeKm?: number;
  activeMovementStepId?: string;
  alignTimeSeconds?: number;
  alignElapsedSeconds?: number;
  alignedToTargetId?: string;
  alignedX?: number;
  alignedY?: number;
  warpSpeedAuPerSecond?: number;
  warpRangeKm?: number;
  warpDestinationX?: number;
  warpDestinationY?: number;
  warpRemainingSeconds?: number;
  warpBlockedReason?: string;
  warpDisruptionStrength?: number;
  warpCoreStrength?: number;
  tackleSourceIds?: string[];
  interdictionRadiusKm?: number;
  interdictionNullified?: boolean;
  burstSourceNames?: string[];
  burstPropulsionSpeedMultiplier?: number;
  burstTackleRangeMultiplier?: number;
  burstEwarRangeMultiplier?: number;
  burstEwarStrengthMultiplier?: number;
  burstSensorStrengthMultiplier?: number;
  burstShieldDamageMultiplier?: number;
  burstArmorDamageMultiplier?: number;
  burstShieldHpMultiplier?: number;
  burstArmorHpMultiplier?: number;
  burstShieldRepairCycleMultiplier?: number;
  burstArmorRepairCycleMultiplier?: number;
};

export type WargameEngineEventKind = "order" | "ai" | "ewar" | "damage" | "repair" | "movement" | "warp" | "combat" | "resolution";

export type WargameEngineEvent = {
  id: string;
  at: number;
  kind: WargameEngineEventKind;
  message: string;
  unitId?: string;
  targetId?: string;
};

export type WargameSimulationOutcome = "blue" | "red" | "draw" | null;

export type WargameAdvanceOptions = {
  elapsedSeconds: number;
  seconds: number;
  redAiEnabled: boolean;
  rngSeed?: number;
  interdictionZones?: WargameInterdictionZone[];
};

export type WargameAdvanceResult = {
  units: WargameUnit[];
  elapsedSeconds: number;
  events: WargameEngineEvent[];
  damageOccurred: boolean;
  combatResolved: boolean;
  outcome: WargameSimulationOutcome;
  rngSeed: number;
};
